(() => {
'use strict';
const CONFIG={apiUrl:'https://script.google.com/macros/s/AKfycbz1LJHQEAZNk-ObztTPVjwwBcV5GZms1uP4AYDSmws1bK62JopArQMRqOy-SFLwQI4m/exec',googleClientId:'626070627425-m3ts9u0ppomue3iq30k16q6n70fgvl3k.apps.googleusercontent.com'};
const DEMO=CONFIG.googleClientId.startsWith('YOUR_');
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={sessionId:'',parent:null,dashboard:null,activeChild:'',admin:null,pendingFlow:'',driveItems:[],demoMode:false};
const demo=createDemo();
document.addEventListener('DOMContentLoaded',init);
function init(){
 $('#year').textContent=new Date().getFullYear();
 $$('.reveal').forEach(el=>new IntersectionObserver((entries,ob)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ob.unobserve(e.target)}}),{threshold:.12}).observe(el));
 $$('[data-open-portal]').forEach(b=>b.addEventListener('click',()=>open('portal-dialog')));$$('[data-open-admin]').forEach(b=>b.addEventListener('click',()=>open('admin-dialog')));$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('[data-close-viewer]').addEventListener('click',()=>$('#viewer-dialog').close());
 $('#trial-form').addEventListener('submit',trial);$('#google-parent-login').addEventListener('click',()=>googleStart('parent'));$('#google-admin-login').addEventListener('click',()=>googleStart('admin'));$('#demo-parent-login').addEventListener('click',()=>demoLogin('parent'));$('#demo-admin-login').addEventListener('click',()=>demoLogin('admin'));$('#parent-logout').addEventListener('click',parentLogout);$('#admin-logout').addEventListener('click',adminLogout);$('#notification-button').addEventListener('click',()=>$('#notification-panel').classList.toggle('hidden'));
 $('#admin-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-admin-tab]');if(!b)return;$$('#admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));adminPanel(b.dataset.adminTab)});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close())});
}
function open(id){$('#'+id).showModal()}function clean(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&','<':'<','>':'>',"'":''','"':'"'}[c]))}function date(v){if(!v)return'Not set';const d=new Date(v);return isNaN(d)?v:d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}function setStatus(el,text='',type=''){el.textContent=text;el.className='form-status '+type}function device(){let id=localStorage.getItem('eduwave_device');if(!id){id=crypto.randomUUID?crypto.randomUUID():Date.now()+'';localStorage.setItem('eduwave_device',id)}return id}
async function api(action,payload={}){if(state.demoMode)return demo(action,payload);if(CONFIG.apiUrl.startsWith('YOUR_'))throw new Error('The portal API URL has not been configured.');const r=await fetch(CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const data=await r.json();if(!data.ok)throw new Error(data.message||'Request failed');return data.data}
async function trial(e){e.preventDefault();const form=e.currentTarget,target=$('#trial-status');if(!form.reportValidity())return;setStatus(target,'Sending your request...');try{await api('submitTrial',Object.fromEntries(new FormData(form)));form.reset();setStatus(target,DEMO?'Trial request saved in the demo queue.':'Request received. The academy will confirm a slot.','success')}catch(err){setStatus(target,err.message,'error')}}
function googleStart(flow){state.pendingFlow=flow;const target=flow==='parent'?$('#portal-auth-status'):$('#admin-auth-status');if(DEMO){setStatus(target,'Add the Apps Script URL and Google client ID to enable the approved-account sign-in. The demo below exercises the complete portal.');return}if(!window.google){const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=showGoogle;document.head.append(s)}else showGoogle()}
function showGoogle(){google.accounts.id.initialize({client_id:CONFIG.googleClientId,callback:googleDone,auto_select:false,cancel_on_tap_outside:true});google.accounts.id.prompt()}
async function googleDone(res){state.demoMode=false;const flow=state.pendingFlow,target=flow==='parent'?$('#portal-auth-status'):$('#admin-auth-status');setStatus(target,'Checking the approved account...');try{if(flow==='parent')applyParent(await api('googleLogin',{idToken:res.credential,deviceId:device(),deviceLabel:navigator.platform||'Browser'}));else{state.admin={idToken:res.credential,data:await api('adminDashboard',{idToken:res.credential})};applyAdmin()}}catch(err){setStatus(target,err.message,'error')}}
async function demoLogin(flow){state.demoMode=true;if(flow==='parent')applyParent(await demo('googleLogin',{demo:true,deviceId:device()}));else{state.admin={idToken:'demo-admin',data:await demo('adminDashboard',{demo:true})};applyAdmin()}}
function applyParent(data){state.sessionId=data.sessionId;state.parent=data.parent;state.dashboard=data.dashboard;state.activeChild=data.dashboard.children[0]?.student_id||'';$('#portal-auth').classList.add('hidden');$('#parent-app').classList.remove('hidden');$('#parent-greeting').textContent=`Hello, ${data.parent.name.split(' ')[0]}`;renderParent();$('#notification-panel').classList.remove('hidden')}
async function parentLogout(){try{await api('logout',{sessionId:state.sessionId})}catch(_){ }state.sessionId='';state.demoMode=false;$('#parent-app').classList.add('hidden');$('#portal-auth').classList.remove('hidden');$('#portal-dialog').close()}
function child(){return state.dashboard.children.find(x=>x.student_id===state.activeChild)}
function renderParent(){const children=state.dashboard.children,active=child();$('#child-tabs').innerHTML=children.map(x=>`<button type="button" class="${x.student_id===state.activeChild?'active':''}" data-child="${clean(x.student_id)}">${clean(x.name)} <small>(Class ${clean(x.class_level)})</small></button>`).join('');$$('[data-child]').forEach(b=>b.addEventListener('click',()=>{state.activeChild=b.dataset.child;renderParent()}));const notes=state.dashboard.notifications.filter(n=>!n.student_id||n.student_id===state.activeChild);$('#notification-count').textContent=notes.length;$('#notification-panel').innerHTML=notes.length?notes.map(n=>`<div class="notification"><b>${clean(n.type)}</b><strong>${clean(n.title)}</strong><br>${clean(n.message)}</div>`).join(''):'<div class="notification">No updates right now.</div>';if(!active){$('#parent-dashboard').innerHTML='<div class="notice">No child is linked to this approved parent account.</div>';return}
 const resources=active.resources.length?active.resources.map(r=>`<div class="resource-row"><button type="button" data-resource="${clean(r.resource_id)}"><span>${clean(r.title)}</span><small>${clean(r.subject||'Learning material')} � ${clean(r.kind)}</small></button>${r.due_date?`<span class="status-pill">Due ${clean(date(r.due_date))}</span>`:'<span class="status-pill">Ready</span>'}</div>`).join(''):'<div class="notice">The academy has not assigned material yet.</div>';
 const fees=active.fees.length?active.fees.map(f=>`<div class="fee-row"><div><b>Rs ${clean(f.amount)} � ${clean(f.billing_month)}</b><small>Due ${clean(date(f.due_date))}${f.reference?` � Ref ${clean(f.reference)}`:''}</small></div><span class="status-pill ${clean(f.status)}">${clean(f.status.replace('_',' '))}</span>${f.status!=='paid'?`<button class="text-button" data-pay="${clean(f.fee_id)}">Pay note</button>`:''}</div>`).join(''):'<div class="notice">No fee record is due right now.</div>';
 const attendance=active.attendance.length?active.attendance.map(x=>`<div class="attendance-row"><div><b>${clean(x.subject)}</b><small>${clean(date(x.session_date))}${x.note?` � ${clean(x.note)}`:''}</small></div><span class="status-pill">${clean(x.status)}</span></div>`).join(''):'<div class="notice">Attendance updates will appear here.</div>';
 const progress=active.progress.length?active.progress.map(x=>`<div class="progress-row"><div><b>${clean(x.topic)}</b><small>${clean(x.subject)}${x.teacher_note?` � ${clean(x.teacher_note)}`:''}</small></div><span class="status-pill">${clean(x.score||'noted')}</span></div>`).join(''):'<div class="notice">Progress notes will appear here.</div>';
 $('#parent-dashboard').innerHTML=`<section class="dashboard-hero"><div><p>CLASS ${clean(active.class_level)}</p><h3>${clean(active.name)}�s learning space</h3><p>${active.resources.length} learning item${active.resources.length===1?'':'s'} currently available.</p></div><button class="button button-dark" id="quick-updates" type="button">View ${notes.length} update${notes.length===1?'':'s'}</button></section><div class="dashboard-grid"><section class="dash-card"><h4>Assignments & materials</h4><div class="resource-list">${resources}</div></section><section class="dash-card"><h4>Fee status</h4><div class="fee-list">${fees}</div></section></div><div class="two-cards"><section class="dash-card"><h4>Recent attendance</h4><div class="attendance-list">${attendance}</div></section><section class="dash-card"><h4>Teacher notes & progress</h4><div class="progress-list">${progress}</div></section></div>`;
 $('#quick-updates').addEventListener('click',()=>$('#notification-panel').classList.toggle('hidden'));$$('[data-resource]').forEach(b=>b.addEventListener('click',()=>resource(b.dataset.resource)));$$('[data-pay]').forEach(b=>b.addEventListener('click',()=>payment(b.dataset.pay)));
}
async function resource(resourceId){const d=$('#viewer-dialog');$('#viewer-content').innerHTML='<div class="viewer-frame">Loading secure preview...</div>';d.showModal();try{const view=await api('parentResource',{sessionId:state.sessionId,studentId:state.activeChild,resourceId});let body;if(view.kind==='table')body=`<table class="viewer-table">${view.values.map(r=>`<tr>${r.map(c=>`<td>${clean(c)}</td>`).join('')}</tr>`).join('')}</table>`;else if(view.kind==='text')body=`<div class="viewer-text">${clean(view.text)}</div>`;else if(view.kind==='image')body=`<img class="viewer-image" alt="${clean(view.title)}" src="${view.data_url}">`;else if(view.kind==='pdf')body=`<iframe class="viewer-pdf" title="${clean(view.title)}" src="${view.data_url}"></iframe>`;else body=`<div class="notice">${clean(view.message)}</div>`;$('#viewer-content').innerHTML=`<div class="viewer-frame"><span class="watermark">${clean(view.watermark||'Eduwave secure preview')}</span><h2>${clean(view.title)}</h2>${body}</div>`;api('parentEvent',{sessionId:state.sessionId,event:'resource_viewed',entityType:'resource',entityId:resourceId,detail:'viewer_open'}).catch(()=>{})}catch(err){$('#viewer-content').innerHTML=`<div class="viewer-frame"><div class="notice">${clean(err.message)}</div></div>`}}
function payment(feeId){const f=child().fees.find(x=>x.fee_id===feeId),t=$('#payment-template').content.cloneNode(true),form=$('.payment-form',t),card=document.createElement('section');card.className='dash-card';card.innerHTML=`<h4>Payment for ${clean(f.billing_month)}</h4><p class="form-status">Pay by UPI${state.dashboard.upiId?` to ${clean(state.dashboard.upiId)}`:' using the academy instructions'}, then submit the reference.</p>`;form.addEventListener('submit',async e=>{e.preventDefault();const out=$('.form-status',form);setStatus(out,'Submitting payment note...');try{await api('parentPaymentNote',{sessionId:state.sessionId,studentId:state.activeChild,feeId,...Object.fromEntries(new FormData(form))});setStatus(out,'Submitted for academy verification.','success');refreshParent()}catch(err){setStatus(out,err.message,'error')}});card.append(t);$('#parent-dashboard').prepend(card);card.scrollIntoView({behavior:'smooth'})}
async function refreshParent(){const d=await api('parentDashboard',{sessionId:state.sessionId});state.parent=d.parent;state.dashboard=d.dashboard;renderParent()}
function applyAdmin(){$('#admin-auth').classList.add('hidden');$('#admin-app').classList.remove('hidden');renderAdmin()}
function adminLogout(){state.admin=null;$('#admin-app').classList.add('hidden');$('#admin-auth').classList.remove('hidden');$('#admin-dialog').close()}
function options(items,value,label){return`<option value="">Select</option>${items.map(x=>`<option value="${clean(x[value])}">${clean(x[label])}</option>`).join('')}`}
function renderAdmin(){const d=state.admin.data;$('#admin-metrics').innerHTML=[['Approved parents',d.metrics.parents],['Active students',d.metrics.students],['Pending trials',d.metrics.pendingTrials],['Open fees',d.metrics.openFees]].map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');adminPanel($('.admin-tabs button.active').dataset.adminTab)}
function adminPanel(tab){const d=state.admin.data,root=$('#admin-content');
 if(tab==='families')root.innerHTML=`<section class="admin-panel"><h3>Families, not spreadsheets.</h3><div class="admin-grid"><article class="admin-card"><h4>Add approved parent</h4><form id="family-form"><label>Parent name<input required name="name"></label><label>Approved Gmail<input required name="email" type="email"></label><label>WhatsApp number<input required name="phone" inputmode="tel"></label><button class="button button-dark">Create parent</button><p class="form-status"></p></form></article><article class="admin-card"><h4>Add a child</h4><form id="student-form"><label>Parent<select required name="parentId">${options(d.parents,'parent_id','name')}</select></label><label>Child name<input required name="name"></label><label>Class<input required name="classLevel" placeholder="e.g. 8"></label><div class="form-row"><label>Monthly fee<input name="monthlyFee" inputmode="numeric"></label><label>Due day<input name="dueDay" type="number" min="1" max="28" value="10"></label></div><button class="button button-dark">Create child</button><p class="form-status"></p></form></article><article class="admin-card"><h4>Approved parents</h4><div class="data-list">${d.parents.map(x=>`<div class="data-line"><b>${clean(x.name)}</b><small>${clean(x.email)} � ${clean(x.phone||'No phone')}</small></div>`).join('')||'<div class="notice">No approved parent yet.</div>'}</div></article><article class="admin-card"><h4>Active children</h4><div class="data-list">${d.students.map(x=>`<div class="data-line"><b>${clean(x.name)} � Class ${clean(x.class_level)}</b><small>Fee Rs ${clean(x.monthly_fee||x.monthlyFee||'not set')} � due ${clean(x.due_day||x.dueDay||'?')}</small></div>`).join('')||'<div class="notice">No child yet.</div>'}</div></article></div></section>`;
 if(tab==='learning')root.innerHTML=`<section class="admin-panel"><h3>Classroom updates</h3><div class="admin-grid"><article class="admin-card"><h4>Exam or class notice</h4><form id="announcement-form"><label>Audience<select name="audience"><option value="all">All parents</option><option value="student">Specific child</option></select></label><label>Child (optional)<select name="studentId">${options(d.students,'student_id','name')}</select></label><label>Title<input required name="title" placeholder="e.g. Maths revision test"></label><label>Message<textarea required name="message" rows="3"></textarea></label><input type="hidden" name="type" value="exam"><button class="button button-dark">Publish notice</button><p class="form-status"></p></form></article><article class="admin-card"><h4>Attendance</h4><form id="attendance-form"><label>Child<select required name="studentId">${options(d.students,'student_id','name')}</select></label><div class="form-row"><label>Date<input required name="sessionDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Subject<input required name="subject"></label></div><label>Status<select name="status"><option>present</option><option>absent</option><option>rescheduled</option></select></label><label>Note<input name="note"></label><button class="button button-dark">Save attendance</button><p class="form-status"></p></form></article><article class="admin-card"><h4>Progress note</h4><form id="progress-form"><label>Child<select required name="studentId">${options(d.students,'student_id','name')}</select></label><div class="form-row"><label>Subject<input required name="subject"></label><label>Score / status<input name="score" placeholder="e.g. 8/10"></label></div><label>Topic<input required name="topic"></label><label>Teacher note<textarea name="note" rows="2"></textarea></label><button class="button button-dark">Add progress note</button><p class="form-status"></p></form></article><article class="admin-card"><h4>Curre... (line truncated to 2000 chars)