/* Eduwave trial portal. Bind to the academy spreadsheet; run setupEduwave() once. */
const PORTAL = { parents:'Portal_Parents', students:'Portal_Students', links:'Portal_ParentStudents', sessions:'Portal_Sessions', loginCodes:'Portal_LoginCodes', trials:'Portal_Trials', fees:'Portal_Fees', driveIndex:'Portal_DriveIndex', resources:'Portal_Resources', assignments:'Portal_Assignments', worksheetRows:'Portal_WorksheetRows', submissions:'Portal_Submissions', attendance:'Portal_Attendance', progress:'Portal_Progress', announcements:'Portal_Announcements', reminders:'Portal_Reminders', audit:'Portal_AuditLogs', config:'Portal_Config' };
const HEADERS = {};
HEADERS[PORTAL.parents] = ['parent_id','name','email','phone','status','created_at','updated_at','email_verified_at'];
HEADERS[PORTAL.students] = ['student_id','name','class_level','enrollment_status','monthly_fee','due_day','created_at','updated_at'];
HEADERS[PORTAL.links] = ['link_id','parent_id','student_id','relationship','active','created_at'];
HEADERS[PORTAL.sessions] = ['session_id','parent_id','device_hash','label','created_at','last_seen_at','expires_at','revoked_at','revoke_reason','role','email'];
HEADERS[PORTAL.loginCodes] = ['code_id','email','role','code_hmac','device_hash','created_at','expires_at','attempts','used_at'];
HEADERS[PORTAL.trials] = ['trial_id','child_name','class_level','parent_name','phone','email','subjects','preferred_slot','notes','status','created_at','updated_at'];
HEADERS[PORTAL.fees] = ['fee_id','student_id','billing_month','amount','due_date','status','paid_date','reference','parent_note','updated_at'];
HEADERS[PORTAL.driveIndex] = ['drive_id','parent_drive_id','path','name','mime_type','kind','owner_email','ownership','size_bytes','modified_at','indexed_at','safe_candidate'];
HEADERS[PORTAL.resources] = ['resource_id','drive_id','title','subject','class_level','kind','status','created_at','updated_at','submission_type'];
HEADERS[PORTAL.assignments] = ['assignment_id','student_id','resource_id','title_override','visible_from','due_date','status','created_at'];
HEADERS[PORTAL.worksheetRows] = ['resource_id','row_no','question','hint'];
HEADERS[PORTAL.submissions] = ['submission_id','assignment_id','student_id','resource_id','responses_json','student_note','status','submitted_at','updated_at','reviewed_at','feedback','attachment_drive_id','attachment_name','attachment_mime','attachment_size'];
HEADERS[PORTAL.attendance] = ['attendance_id','student_id','session_date','subject','status','note','updated_at'];
HEADERS[PORTAL.progress] = ['progress_id','student_id','subject','topic','score','teacher_note','updated_at'];
HEADERS[PORTAL.announcements] = ['announcement_id','audience','student_id','title','message','type','active_from','active_until','created_at'];
HEADERS[PORTAL.reminders] = ['reminder_id','student_id','type','message','created_at','sent_at','status','whatsapp_url'];
HEADERS[PORTAL.audit] = ['event_id','actor_type','actor_id','event','entity_type','entity_id','detail','created_at'];
HEADERS[PORTAL.config] = ['key','value','updated_at'];
const SESSION_IDLE_MINUTES = 60, ADMIN_IDLE_MINUTES = 30, SESSION_ABSOLUTE_HOURS = 12, ADMIN_ABSOLUTE_HOURS = 8, MAX_ACTIVE_SESSIONS = 1, OTP_EXPIRY_MINUTES = 10, OTP_REQUEST_LIMIT = 3, OTP_WINDOW_MINUTES = 15, OTP_MAX_ATTEMPTS = 5, MAX_UPLOAD_BYTES = 8*1024*1024, MAX_BINARY_BYTES = 10*1024*1024, TZ = Session.getScriptTimeZone() || 'Asia/Kolkata';
const STUDENT_UPLOAD_MIMES = ['application/pdf','image/jpeg','image/png'];
const ACADEMY_UPLOAD_MIMES = STUDENT_UPLOAD_MIMES.concat(['application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/rtf','text/rtf','text/plain']);
function onOpen(){ SpreadsheetApp.getUi().createMenu('Eduwave Portal').addItem('Create portal tabs safely','setupEduwave').addItem('Upgrade protected file uploads','upgradeFileUploads').addItem('Authorize login email','authorizeEduwaveMail').addItem('Create this month\'s fee rows','generateMonthlyFees').addToUi(); }
function setupEduwave(){ Object.keys(HEADERS).forEach(ensureHeaders_);authSecret_();setConfigDefault_('admin_email','studywitheduwaveacademy@gmail.com');setConfigDefault_('developer_email','diwij.narang2001@gmail.com');setConfigDefault_('drive_root_id','');setConfigDefault_('portal_upload_root_id','');setConfigDefault_('resource_upload_folder_id','');setConfigDefault_('submission_upload_folder_id','');setConfigDefault_('upi_id','');setConfigDefault_('academy_name','Eduwave Academy');audit_('system','setup','setup','workbook',SpreadsheetApp.getActive().getId(),'Portal tabs, secure email login, and protected uploads are ready; legacy tabs untouched.');try{SpreadsheetApp.getActive().toast('Portal tabs, login, and protected uploads are ready.','Eduwave Portal',5);}catch(_){ }return{ready:true,auth:'email_otp',tabs:Object.keys(HEADERS)}; }
function upgradeFileUploads(){[PORTAL.resources,PORTAL.submissions,PORTAL.config].forEach(ensureHeaders_);setConfigDefault_('portal_upload_root_id','');setConfigDefault_('resource_upload_folder_id','');setConfigDefault_('submission_upload_folder_id','');try{SpreadsheetApp.getActive().toast('Protected file uploads are ready.','Eduwave Portal',5);}catch(_){ }return{ready:true,resources:HEADERS[PORTAL.resources],submissions:HEADERS[PORTAL.submissions]};}
function authorizeEduwaveMail(){var quota=MailApp.getRemainingDailyQuota();try{SpreadsheetApp.getActive().toast('Login email is authorized. Remaining daily quota: '+quota+'.','Eduwave Portal',5);}catch(_){ }return{authorized:true,remainingDailyQuota:quota};}
function generateMonthlyFees(){var r=generateMonthlyFees_();SpreadsheetApp.getUi().alert('Created '+r.created+' fee row(s) for '+r.month+'.');}
function doGet(){return json_(true,'Eduwave portal API is online.',{version:'3.2',auth:'email_otp',configured:!!getConfig_('admin_email')});}
function doPost(e){try{var p=JSON.parse((e&&e.postData&&e.postData.contents)||'{}'),a=clean_(p.action),d;if(!a)throw new Error('Missing action.');switch(a){case'health':d={version:'3.2',auth:'email_otp',configured:!!getConfig_('admin_email')};break;case'submitTrial':d=submitTrial_(p);break;case'signupParent':d=signupParent_(p);break;case'requestLoginCode':d=requestLoginCode_(p);break;case'verifyLoginCode':d=verifyLoginCode_(p);break;case'logout':d=logout_(p);break;case'parentDashboard':d=parentDashboard_(p);break;case'parentResource':d=parentResource_(p);break;case'parentSubmitAssignment':d=parentSubmitAssignment_(p);break;case'parentPaymentNote':d=parentPaymentNote_(p);break;case'parentEvent':d=parentEvent_(p);break;case'adminDashboard':d=adminDashboard_(p);break;case'adminCreateFamily':d=adminCreateFamily_(p);break;case'adminSetParentStatus':d=adminSetParentStatus_(p);break;case'adminCreateStudent':d=adminCreateStudent_(p);break;case'adminApproveTrial':d=adminApproveTrial_(p);break;case'adminCreateAnnouncement':d=adminCreateAnnouncement_(p);break;case'adminRecordAttendance':d=adminRecordAttendance_(p);break;case'adminRecordProgress':d=adminRecordProgress_(p);break;case'adminReviewSubmission':d=adminReviewSubmission_(p);break;case'adminSubmissionFile':d=adminSubmissionFile_(p);break;case'adminGenerateMonthlyFees':requireAdmin_(p.sessionId);d=generateMonthlyFees_();break;case'adminMarkFeePaid':d=adminMarkFeePaid_(p);break;case'adminQueueReminder':d=adminQueueReminder_(p);break;case'adminDriveFolders':d=adminDriveFolders_(p);break;case'adminScanDrive':d=adminScanDrive_(p);break;case'adminDriveItems':d=adminDriveItems_(p);break;case'adminCreateResource':d=adminCreateResource_(p);break;case'adminUploadResource':d=adminUploadResource_(p);break;case'adminAssignResource':d=adminAssignResource_(p);break;default:throw new Error('Unknown action.');}return json_(true,'Success',d);}catch(err){return json_(false,err&&err.message?err.message:'Server error');}}
function submitTrial_(p){['childName','classLevel','parentName','phone','email','subjects','preferredSlot'].forEach(function(k){if(!clean_(p[k]))throw new Error('Please complete all required trial fields.');});var now=stamp_();append_(PORTAL.trials,{trial_id:id_('TRIAL'),child_name:clean_(p.childName),class_level:clean_(p.classLevel),parent_name:clean_(p.parentName),phone:clean_(p.phone),email:email_(p.email),subjects:clean_(p.subjects),preferred_slot:clean_(p.preferredSlot),notes:clean_(p.notes),status:'pending',created_at:now,updated_at:now});audit_('public',email_(p.email),'trial_requested','trial','',clean_(p.childName));return{recorded:true};}
function signupParent_(p){if(clean_(p.website))return{recorded:true};var name=clean_(p.name),email=validEmail_(p.email),phone=clean_(p.phone);if(!name||!email)throw new Error('Enter the parent name and a valid email address.');var lock=LockService.getScriptLock();lock.waitLock(10000);try{var old=first_(PORTAL.parents,function(r){return email_(r.email)===email;});if(!old)append_(PORTAL.parents,{parent_id:id_('PAR'),name:name,email:email,phone:phone,status:'pending',created_at:stamp_(),updated_at:stamp_(),email_verified_at:''});else if(clean_(old.status).toLowerCase()==='pending')update_(PORTAL.parents,old._row,{name:name,phone:phone||old.phone,updated_at:stamp_()});}finally{lock.releaseLock();}audit_('public',email,'parent_signup_requested','parent','',name);return{recorded:true};}
function requestLoginCode_(p){var email=validEmail_(p.email),role=clean_(p.role).toLowerCase()==='admin'?'admin':'parent',device=clean_(p.deviceId)||'unknown-device',eligible=false,actorId='';if(!email)throw new Error('Enter a valid email address.');if(role==='admin'){eligible=adminEmails_().indexOf(email)!==-1;actorId=email;}else{var parent=first_(PORTAL.parents,function(r){return email_(r.email)===email&&clean_(r.status).toLowerCase()==='active';});eligible=!!parent;actorId=parent?parent.parent_id:email;}if(!eligible)return{sent:true,expiresMinutes:OTP_EXPIRY_MINUTES};var lock=LockService.getScriptLock();lock.waitLock(10000);try{var now=Date.now(),recent=rows_(PORTAL.loginCodes).filter(function(r){var created=Date.parse(r.created_at);return r.email===email&&r.role===role&&created&&!isNaN(created)&&now-created<OTP_WINDOW_MINUTES*60000;});if(recent.length>=OTP_REQUEST_LIMIT){audit_('system',actorId,'login_code_rate_limited',role,'',email);return{sent:true,expiresMinutes:OTP_EXPIRY_MINUTES};}if(mailQuota_()<1)throw new Error('Login email service is temporarily unavailable. Please contact the academy.');rows_(PORTAL.loginCodes).filter(function(r){return r.email===email&&r.role===role&&!r.used_at;}).forEach(function(r){update_(PORTAL.loginCodes,r._row,{used_at:stamp_()});});var codeId=id_('OTP'),code=otp_(),row={code_id:codeId,email:email,role:role,code_hmac:authHash_('otp|'+codeId+'|'+email+'|'+role+'|'+code),device_hash:hash_(device),created_at:stamp_(),expires_at:stamp_(new Date(now+OTP_EXPIRY_MINUTES*60000)),attempts:'0',used_at:''};append_(PORTAL.loginCodes,row);try{sendLoginCode_(email,code,role);}catch(err){var saved=first_(PORTAL.loginCodes,function(r){return r.code_id===codeId;});if(saved)update_(PORTAL.loginCodes,saved._row,{used_at:stamp_()});throw err;}audit_('system',actorId,'login_code_sent',role,codeId,email);}finally{lock.releaseLock();}return{sent:true,expiresMinutes:OTP_EXPIRY_MINUTES};}
function verifyLoginCode_(p){var email=validEmail_(p.email),role=clean_(p.role).toLowerCase()==='admin'?'admin':'parent',code=clean_(p.code),device=clean_(p.deviceId)||'unknown-device';if(!email||!/^[0-9]{6}$/.test(code))throw new Error('Enter the six-digit code from your email.');var lock=LockService.getScriptLock();lock.waitLock(10000);try{var row=rows_(PORTAL.loginCodes).filter(function(r){return r.email===email&&r.role===role&&!r.used_at&&r.device_hash===hash_(device);}).sort(newest_)[0];if(!row||row.expires_at<stamp_()||Number(row.attempts)>=OTP_MAX_ATTEMPTS){if(row&&!row.used_at)update_(PORTAL.loginCodes,row._row,{used_at:stamp_()});throw new Error('That code is invalid or expired. Request a new code.');}var expected=authHash_('otp|'+row.code_id+'|'+email+'|'+role+'|'+code);if(!safeEqual_(expected,row.code_hmac)){var attempts=Number(row.attempts||0)+1;update_(PORTAL.loginCodes,row._row,{attempts:String(attempts),used_at:attempts>=OTP_MAX_ATTEMPTS?stamp_():''});throw new Error('That code is invalid or expired. Request a new code.');}update_(PORTAL.loginCodes,row._row,{used_at:stamp_()});}finally{lock.releaseLock();}if(role==='admin'){if(adminEmails_().indexOf(email)===-1)throw new Error('This email is not approved for academy access.');var admin={email:email,access_role:academyRole_(email)},adminSession=createSession_('admin',email,'',p);audit_(admin.access_role,email,'login','session','',clean_(p.deviceLabel));return{role:'admin',sessionId:adminSession,dashboard:adminData_(admin)};}var parent=first_(PORTAL.parents,function(r){return email_(r.email)===email&&clean_(r.status).toLowerCase()==='active';});if(!parent)throw new Error('This parent account is awaiting academy approval.');update_(PORTAL.parents,parent._row,{email_verified_at:stamp_(),updated_at:stamp_()});parent.email_verified_at=stamp_();var parentSession=createSession_('parent',email,parent.parent_id,p);audit_('parent',parent.parent_id,'login','session','',clean_(p.deviceLabel));return{role:'parent',sessionId:parentSession,parent:parentView_(parent),dashboard:dashboardForParent_(parent)};}
function createSession_(role,email,parentId,p){var now=new Date(),active=rows_(PORTAL.sessions).filter(function(r){return r.role===role&&r.email===email&&!r.revoked_at&&r.expires_at>stamp_(now);}).sort(function(a,b){return String(a.created_at).localeCompare(String(b.created_at));});while(active.length>=MAX_ACTIVE_SESSIONS){var oldest=active.shift();update_(PORTAL.sessions,oldest._row,{revoked_at:stamp_(),revoke_reason:'new_login'});audit_('system',email,'session_revoked','session','','A newer login replaced this session.');}var raw=token_(),hours=role==='admin'?ADMIN_ABSOLUTE_HOURS:SESSION_ABSOLUTE_HOURS;append_(PORTAL.sessions,{session_id:authHash_('session|'+raw),parent_id:parentId,device_hash:hash_(clean_(p.deviceId)||'unknown-device'),label:clean_(p.deviceLabel)||'Browser',created_at:stamp_(),last_seen_at:stamp_(),expires_at:stamp_(new Date(now.getTime()+hours*3600000)),revoked_at:'',revoke_reason:'',role:role,email:email});return raw;}
function logout_(p){var s=session_(p.sessionId,false);if(s)update_(PORTAL.sessions,s._row,{revoked_at:stamp_(),revoke_reason:'logout'});return{loggedOut:true};}
function parentDashboard_(p){var parent=parentFromSession_(p.sessionId);return{parent:parentView_(parent),dashboard:dashboardForParent_(parent)};}
function parentResource_(p){var parent=parentFromSession_(p.sessionId),studentId=clean_(p.studentId);requireLinkedStudent_(parent.parent_id,studentId);var asn=first_(PORTAL.assignments,function(r){return r.student_id===studentId&&r.resource_id===clean_(p.resourceId)&&clean_(r.status).toLowerCase()==='published';});if(!asn)throw new Error('This resource is not assigned to this child.');var resource=first_(PORTAL.resources,function(r){return r.resource_id===asn.resource_id&&clean_(r.status).toLowerCase()==='published';});if(!resource)throw new Error('This resource is not available.');audit_('parent',parent.parent_id,'resource_open','resource',resource.resource_id,studentId);if(clean_(resource.kind).toLowerCase()==='worksheet')return renderPortalWorksheet_(resource,parent,studentId,asn);var item=first_(PORTAL.driveIndex,function(r){return r.drive_id===resource.drive_id;});if(!item||clean_(item.safe_candidate).toLowerCase()!=='true')throw new Error('This item has not been approved for portal viewing.');return renderDriveItem_(item,resource,parent,studentId,asn);}
function parentSubmitAssignment_(p){
  var parent=parentFromSession_(p.sessionId),studentId=clean_(p.studentId),assignmentId=clean_(p.assignmentId);
  requireLinkedStudent_(parent.parent_id,studentId);
  var asn=first_(PORTAL.assignments,function(r){return r.assignment_id===assignmentId&&r.student_id===studentId&&clean_(r.status).toLowerCase()==='published';});
  if(!asn)throw new Error('This assignment is not available.');
  var resource=first_(PORTAL.resources,function(r){return r.resource_id===asn.resource_id&&clean_(r.status).toLowerCase()==='published';});
  if(!resource)throw new Error('This resource is not available.');
  var type=submissionType_(resource),old=first_(PORTAL.submissions,function(r){return r.assignment_id===assignmentId&&r.student_id===studentId;});
  if(type==='view_only')throw new Error('This material does not require a submission.');
  if(old&&clean_(old.status).toLowerCase()==='reviewed')throw new Error('This assignment has been reviewed and is now locked.');
  var answers=Array.isArray(p.answers)?p.answers:[],safeAnswers=answers.slice(0,100).map(function(a){return{row:Math.max(1,Number(a.row)||1),question:clean_(a.question).slice(0,500),answer:clean_(a.answer).slice(0,2000)};}).filter(function(a){return a.answer;});
  var note=clean_(p.note).slice(0,3000),uploaded=null;
  if(p.attachment)uploaded=savePortalUpload_(p.attachment,STUDENT_UPLOAD_MIMES,'submission_upload_folder_id','Student Submissions',studentId+'_'+assignmentId+'_');
  if(type==='file_upload'&&!uploaded&&!(old&&old.attachment_drive_id))throw new Error('Attach a PDF, JPG, or PNG scan before submitting.');
  if(type==='online_answers'&&!safeAnswers.length&&!note)throw new Error('Add at least one answer or a note before submitting.');
  var now=stamp_(),v={assignment_id:assignmentId,student_id:studentId,resource_id:asn.resource_id,responses_json:JSON.stringify(safeAnswers),student_note:note,status:'submitted',submitted_at:now,updated_at:now,reviewed_at:'',feedback:''};
  if(uploaded){v.attachment_drive_id=uploaded.file.getId();v.attachment_name=uploaded.name;v.attachment_mime=uploaded.mime;v.attachment_size=String(uploaded.size);}
  if(old)update_(PORTAL.submissions,old._row,v);else{v.submission_id=id_('SUB');append_(PORTAL.submissions,v);}
  if(uploaded&&old&&old.attachment_drive_id&&old.attachment_drive_id!==uploaded.file.getId())trashFile_(old.attachment_drive_id);
  audit_('parent',parent.parent_id,'assignment_submitted','assignment',assignmentId,studentId+(uploaded?' | file uploaded':''));
  return{submitted:true,status:'submitted',submittedAt:now,hasAttachment:!!(uploaded||(old&&old.attachment_drive_id))};
}
function parentPaymentNote_(p){var parent=parentFromSession_(p.sessionId),sid=clean_(p.studentId);requireLinkedStudent_(parent.parent_id,sid);var fee=first_(PORTAL.fees,function(r){return r.fee_id===clean_(p.feeId)&&r.student_id===sid;});if(!fee)throw new Error('Fee record not found.');if(!clean_(p.reference))throw new Error('Add the UPI reference before submitting.');update_(PORTAL.fees,fee._row,{status:'pending_verification',reference:clean_(p.reference),parent_note:clean_(p.note),updated_at:stamp_()});audit_('parent',parent.parent_id,'payment_note_submitted','fee',fee.fee_id,clean_(p.reference));return{submitted:true};}
function parentEvent_(p){var parent=parentFromSession_(p.sessionId);audit_('parent',parent.parent_id,clean_(p.event).slice(0,60),clean_(p.entityType).slice(0,60),clean_(p.entityId).slice(0,80),clean_(p.detail).slice(0,500));return{logged:true};}
function adminDashboard_(p){return adminData_(requireAdmin_(p.sessionId));}
function adminData_(admin){var fees=rows_(PORTAL.fees),trials=rows_(PORTAL.trials),parents=rows_(PORTAL.parents),students=rows_(PORTAL.students),directory=adminFamilyDirectory_(parents,students,rows_(PORTAL.links)),submissions=rows_(PORTAL.submissions).map(submissionView_).sort(newest_);return{admin:admin,metrics:{parents:parents.filter(function(x){return clean_(x.status).toLowerCase()==='active';}).length,pendingParents:parents.filter(function(x){return clean_(x.status).toLowerCase()==='pending';}).length,students:students.filter(function(x){return clean_(x.enrollment_status).toLowerCase()==='active';}).length,pendingTrials:trials.filter(function(x){return clean_(x.status).toLowerCase()==='pending';}).length,openFees:fees.filter(function(x){return clean_(x.status).toLowerCase()!=='paid';}).length},parents:parents.map(parentView_),students:students,families:directory.families,unlinkedStudents:directory.unlinkedStudents,trials:trials.sort(newest_),fees:fees.sort(newest_),resources:rows_(PORTAL.resources).sort(newest_),assignments:rows_(PORTAL.assignments).sort(newest_),submissions:submissions,announcements:rows_(PORTAL.announcements).sort(newest_),reminders:rows_(PORTAL.reminders).sort(newest_).slice(0,50),activity:rows_(PORTAL.audit).sort(newest_).slice(0,50)};}
function adminFamilyDirectory_(parents,students,links){var activeLinks=links.filter(function(r){return clean_(r.active).toLowerCase()==='true';}),linked={};var families=parents.map(function(parent){var children=activeLinks.filter(function(link){return link.parent_id===parent.parent_id;}).map(function(link){var student=students.filter(function(s){return s.student_id===link.student_id;})[0];if(!student)return null;linked[student.student_id]=true;return{student_id:student.student_id,name:student.name,class_level:student.class_level,enrollment_status:student.enrollment_status,monthly_fee:student.monthly_fee,due_day:student.due_day,relationship:link.relationship||'Parent'};}).filter(Boolean).sort(function(a,b){return clean_(a.name).localeCompare(clean_(b.name));});return{parent_id:parent.parent_id,name:parent.name,email:parent.email,phone:parent.phone,status:parent.status,email_verified:!!parent.email_verified_at,children:children};}).sort(function(a,b){var activeA=clean_(a.status).toLowerCase()==='active',activeB=clean_(b.status).toLowerCase()==='active';if(activeA!==activeB)return activeA?-1:1;return clean_(a.name).localeCompare(clean_(b.name));});var unlinkedStudents=students.filter(function(student){return clean_(student.enrollment_status).toLowerCase()==='active'&&!linked[student.student_id];}).map(function(student){return{student_id:student.student_id,name:student.name,class_level:student.class_level,enrollment_status:student.enrollment_status,monthly_fee:student.monthly_fee,due_day:student.due_day};});return{families:families,unlinkedStudents:unlinkedStudents};}
function adminCreateFamily_(p){var admin=requireAdmin_(p.sessionId),email=validEmail_(p.email);if(!email||!clean_(p.name))throw new Error('Parent name and a valid email address are required.');if(first_(PORTAL.parents,function(r){return email_(r.email)===email;}))throw new Error('That parent email address already exists.');var parent={parent_id:id_('PAR'),name:clean_(p.name),email:email,phone:clean_(p.phone),status:'active',created_at:stamp_(),updated_at:stamp_(),email_verified_at:''};append_(PORTAL.parents,parent);audit_('admin',admin.email,'parent_created','parent',parent.parent_id,email);return parentView_(parent);}
function adminSetParentStatus_(p){var admin=requireAdmin_(p.sessionId),parent=first_(PORTAL.parents,function(r){return r.parent_id===clean_(p.parentId);}),status=clean_(p.status).toLowerCase();if(!parent)throw new Error('Parent account not found.');if(['active','denied'].indexOf(status)===-1)throw new Error('Choose approve or deny.');update_(PORTAL.parents,parent._row,{status:status,updated_at:stamp_()});if(status!=='active')rows_(PORTAL.sessions).filter(function(r){return r.parent_id===parent.parent_id&&!r.revoked_at;}).forEach(function(r){update_(PORTAL.sessions,r._row,{revoked_at:stamp_(),revoke_reason:'account_'+status});});audit_('admin',admin.email,'parent_'+status,'parent',parent.parent_id,parent.email);return{updated:true};}
function adminCreateStudent_(p){var admin=requireAdmin_(p.sessionId),parent=first_(PORTAL.parents,function(r){return r.parent_id===clean_(p.parentId)&&clean_(r.status).toLowerCase()==='active';});if(!parent||!clean_(p.name)||!clean_(p.classLevel))throw new Error('Choose an approved parent and complete the child name and class.');var student={student_id:id_('STU'),name:clean_(p.name),class_level:clean_(p.classLevel),enrollment_status:'active',monthly_fee:clean_(p.monthlyFee),due_day:clean_(p.dueDay)||'10',created_at:stamp_(),updated_at:stamp_()};append_(PORTAL.students,student);append_(PORTAL.links,{link_id:id_('LINK'),parent_id:parent.parent_id,student_id:student.student_id,relationship:clean_(p.relationship)||'Parent',active:'true',created_at:stamp_()});audit_('admin',admin.email,'student_created','student',student.student_id,parent.parent_id);return student;}
function adminApproveTrial_(p){var admin=requireAdmin_(p.sessionId),trial=first_(PORTAL.trials,function(r){return r.trial_id===clean_(p.trialId);});if(!trial)throw new Error('Trial request not found.');update_(PORTAL.trials,trial._row,{status:clean_(p.status)||'approved',updated_at:stamp_()});audit_('admin',admin.email,'trial_updated','trial',trial.trial_id,clean_(p.status)||'approved');return{updated:true};}
function adminCreateAnnouncement_(p){var admin=requireAdmin_(p.sessionId);if(!clean_(p.title)||!clean_(p.message))throw new Error('Announcement title and message are required.');var a={announcement_id:id_('ANN'),audience:clean_(p.audience)||'all',student_id:clean_(p.studentId),title:clean_(p.title),message:clean_(p.message),type:clean_(p.type)||'notice',active_from:clean_(p.activeFrom)||date_(),active_until:clean_(p.activeUntil),created_at:stamp_()};append_(PORTAL.announcements,a);audit_('admin',admin.email,'announcement_created','announcement',a.announcement_id,a.title);return a;}
function adminRecordAttendance_(p){var admin=requireAdmin_(p.sessionId);if(!clean_(p.studentId)||!clean_(p.sessionDate)||!clean_(p.subject))throw new Error('Child, date, and subject are required.');var old=first_(PORTAL.attendance,function(r){return r.student_id===clean_(p.studentId)&&r.session_date===clean_(p.sessionDate)&&r.subject===clean_(p.subject);}),v={student_id:clean_(p.studentId),session_date:clean_(p.sessionDate),subject:clean_(p.subject),status:clean_(p.status)||'present',note:clean_(p.note),updated_at:stamp_()};if(old)update_(PORTAL.attendance,old._row,v);else{v.attendance_id=id_('ATT');append_(PORTAL.attendance,v);}audit_('admin',admin.email,'attendance_saved','student',clean_(p.studentId),clean_(p.status));return{saved:true};}
function adminRecordProgress_(p){var admin=requireAdmin_(p.sessionId);if(!clean_(p.studentId)||!clean_(p.subject)||!clean_(p.topic))throw new Error('Child, subject, and topic are required.');var v={progress_id:id_('PROG'),student_id:clean_(p.studentId),subject:clean_(p.subject),topic:clean_(p.topic),score:clean_(p.score),teacher_note:clean_(p.note),updated_at:stamp_()};append_(PORTAL.progress,v);audit_('admin',admin.email,'progress_saved','student',v.student_id,v.topic);return v;}
function adminReviewSubmission_(p){var admin=requireAdmin_(p.sessionId),submission=first_(PORTAL.submissions,function(r){return r.submission_id===clean_(p.submissionId);}),status=clean_(p.status).toLowerCase();if(!submission)throw new Error('Submission not found.');if(['reviewed','needs_changes'].indexOf(status)===-1)throw new Error('Choose reviewed or needs changes.');update_(PORTAL.submissions,submission._row,{status:status,feedback:clean_(p.feedback).slice(0,3000),reviewed_at:stamp_(),updated_at:stamp_()});audit_('admin',admin.email,'assignment_'+status,'submission',submission.submission_id,submission.student_id);return{reviewed:true,status:status};}
function adminSubmissionFile_(p){var admin=requireAdmin_(p.sessionId),submission=first_(PORTAL.submissions,function(r){return r.submission_id===clean_(p.submissionId);});if(!submission||!submission.attachment_drive_id)throw new Error('This submission has no uploaded file.');var file=DriveApp.getFileById(submission.attachment_drive_id);if(file.getSize()>MAX_BINARY_BYTES)throw new Error('This submitted file is too large to preview.');var blob=file.getBlob(),mime=blob.getContentType(),kind=mime==='application/pdf'?'pdf':/^image\//.test(mime)?'image':'download';audit_('admin',admin.email,'submission_file_opened','submission',submission.submission_id,submission.student_id);return{kind:kind,title:submission.attachment_name||file.getName(),mimeType:mime,data_url:'data:'+mime+';base64,'+Utilities.base64Encode(blob.getBytes())};}
function generateMonthlyFees_(){var month=Utilities.formatDate(new Date(),TZ,'MMMM yyyy'),created=0;rows_(PORTAL.students).filter(function(r){return clean_(r.enrollment_status).toLowerCase()==='active'&&Number(r.monthly_fee)>0;}).forEach(function(s){if(first_(PORTAL.fees,function(f){return f.student_id===s.student_id&&f.billing_month===month;}))return;var due=new Date();due.setDate(Math.max(1,Math.min(28,Number(s.due_day)||10)));append_(PORTAL.fees,{fee_id:id_('FEE'),student_id:s.student_id,billing_month:month,amount:s.monthly_fee,due_date:date_(due),status:'due',paid_date:'',reference:'',parent_note:'',updated_at:stamp_()});created+=1;});audit_('system','monthly-batch','fees_generated','fee',month,String(created));return{created:created,month:month};}
function adminMarkFeePaid_(p){var admin=requireAdmin_(p.sessionId),fee=first_(PORTAL.fees,function(r){return r.fee_id===clean_(p.feeId);});if(!fee)throw new Error('Fee record not found.');update_(PORTAL.fees,fee._row,{status:'paid',paid_date:clean_(p.paidDate)||date_(),reference:clean_(p.reference)||fee.reference,updated_at:stamp_()});audit_('admin',admin.email,'fee_marked_paid','fee',fee.fee_id,fee.student_id);return{paid:true};}
function adminQueueReminder_(p){var admin=requireAdmin_(p.sessionId),student=first_(PORTAL.students,function(r){return r.student_id===clean_(p.studentId);});if(!student)throw new Error('Child not found.');var link=first_(PORTAL.links,function(r){return r.student_id===student.student_id&&clean_(r.active).toLowerCase()==='true';}),parent=link&&first_(PORTAL.parents,function(r){return r.parent_id===link.parent_id;});if(!parent||!clean_(parent.phone))throw new Error('An active parent phone number is required for WhatsApp.');var message=clean_(p.message)||'Hello '+parent.name+', this is an Eduwave Academy update for '+student.name+'.',phone=clean_(parent.phone).replace(/[^0-9]/g,'');if(phone.length===10)phone='91'+phone;var url='https://wa.me/'+phone+'?text='+encodeURIComponent(message);append_(PORTAL.reminders,{reminder_id:id_('REM'),student_id:student.student_id,type:clean_(p.type)||'general',message:message,created_at:stamp_(),sent_at:'',status:'queued',whatsapp_url:url});audit_('admin',admin.email,'reminder_queued','student',student.student_id,clean_(p.type)||'general');return{whatsappUrl:url};}
function adminDriveFolders_(p){var admin=requireAdmin_(p.sessionId),currentId=getConfig_('drive_root_id'),folders=[],seen={},iterator=DriveApp.getRootFolder().getFolders();while(iterator.hasNext()&&folders.length<200){var folder=iterator.next(),id=folder.getId();seen[id]=true;folders.push({folder_id:id,name:folder.getName(),current:id===currentId});}if(currentId&&!seen[currentId]){try{var current=DriveApp.getFolderById(currentId);folders.unshift({folder_id:currentId,name:current.getName(),current:true,legacy:true});}catch(_){ }}folders.sort(function(a,b){if(a.current!==b.current)return a.current?-1:1;return clean_(a.name).localeCompare(clean_(b.name));});audit_('admin',admin.email,'drive_folders_listed','drive','root',String(folders.length));return{folders:folders,currentFolderId:currentId,truncated:folders.length>=200};}
function adminScanDrive_(p){var admin=requireAdmin_(p.sessionId),rootId=clean_(p.rootFolderId)||getConfig_('drive_root_id');if(!rootId)throw new Error('Choose a Drive folder first.');var root=DriveApp.getFolderById(rootId);setConfig_('drive_root_id',rootId);var state={count:0,limit:Math.min(500,Math.max(1,Number(p.limit)||250)),owner:admin.email};scanFolder_(root,root.getName(),state);audit_('admin',admin.email,'drive_scanned','drive',rootId,String(state.count));return{indexed:state.count,truncated:state.count>=state.limit,folderName:root.getName()};}
function scanFolder_(folder,path,state){if(state.count>=state.limit)return;var folders=folder.getFolders();while(folders.hasNext()&&state.count<state.limit){var child=folders.next();scanFolder_(child,path+' / '+child.getName(),state);}var files=folder.getFiles();while(files.hasNext()&&state.count<state.limit){var file=files.next(),owner='';try{owner=file.getOwner()?file.getOwner().getEmail():'';}catch(ignore){}var owned=owner&&email_(owner)===email_(state.owner),safe=owned&&!/^video\//.test(file.getMimeType()),old=first_(PORTAL.driveIndex,function(r){return r.drive_id===file.getId();}),v={drive_id:file.getId(),parent_drive_id:folder.getId(),path:path,name:file.getName(),mime_type:file.getMimeType(),kind:driveKind_(file.getMimeType(),file.getName()),owner_email:owner,ownership:owned?'academy':'external',size_bytes:String(file.getSize()),modified_at:stamp_(file.getLastUpdated()),indexed_at:stamp_(),safe_candidate:String(safe)};if(old)update_(PORTAL.driveIndex,old._row,v);else append_(PORTAL.driveIndex,v);state.count+=1;}}
function adminDriveItems_(p){requireAdmin_(p.sessionId);return rows_(PORTAL.driveIndex).filter(function(r){return clean_(r.ownership)==='academy'&&clean_(r.safe_candidate).toLowerCase()==='true';}).sort(function(a,b){return clean_(a.path+a.name).localeCompare(clean_(b.path+b.name));}).slice(0,500);}
function adminCreateResource_(p){var admin=requireAdmin_(p.sessionId),item=first_(PORTAL.driveIndex,function(r){return r.drive_id===clean_(p.driveId);});if(!item||clean_(item.safe_candidate).toLowerCase()!=='true')throw new Error('Choose an academy-owned, non-video file from the indexed Drive list.');var old=first_(PORTAL.resources,function(r){return r.drive_id===item.drive_id;}),v={drive_id:item.drive_id,title:clean_(p.title)||item.name,subject:clean_(p.subject),class_level:clean_(p.classLevel),kind:item.kind,status:'published',updated_at:stamp_(),submission_type:validSubmissionType_(p.submissionType,item.kind)};if(old){update_(PORTAL.resources,old._row,v);return merge_(old,v);}v.resource_id=id_('RES');v.created_at=stamp_();append_(PORTAL.resources,v);audit_('admin',admin.email,'resource_published','resource',v.resource_id,v.title);return v;}
function adminUploadResource_(p){
  var admin=requireAdmin_(p.sessionId),title=clean_(p.title);
  if(!title)throw new Error('Add a title for this material.');
  var uploaded=savePortalUpload_(p.file,ACADEMY_UPLOAD_MIMES,'resource_upload_folder_id','Resources','');
  var file=uploaded.file,kind=driveKind_(uploaded.mime,uploaded.name),owner='';
  try{owner=file.getOwner()?file.getOwner().getEmail():admin.email;}catch(_){owner=admin.email;}
  append_(PORTAL.driveIndex,{drive_id:file.getId(),parent_drive_id:file.getParents&&file.getParents().hasNext()?file.getParents().next().getId():'',path:'Eduwave Portal Uploads / Resources',name:uploaded.name,mime_type:uploaded.mime,kind:kind,owner_email:owner,ownership:'academy',size_bytes:String(uploaded.size),modified_at:stamp_(),indexed_at:stamp_(),safe_candidate:'true'});
  var resource={resource_id:id_('RES'),drive_id:file.getId(),title:title,subject:clean_(p.subject),class_level:clean_(p.classLevel),kind:kind,status:'published',created_at:stamp_(),updated_at:stamp_(),submission_type:validSubmissionType_(p.submissionType,kind)};
  append_(PORTAL.resources,resource);audit_('admin',admin.email,'resource_uploaded','resource',resource.resource_id,resource.title+' | '+uploaded.name);return resource;
}
function adminAssignResource_(p){var admin=requireAdmin_(p.sessionId);if(!clean_(p.studentId)||!clean_(p.resourceId))throw new Error('Choose a child and a resource.');var r=first_(PORTAL.resources,function(x){return x.resource_id===clean_(p.resourceId)&&clean_(x.status)==='published';});if(!r)throw new Error('Published resource not found.');var old=first_(PORTAL.assignments,function(x){return x.student_id===clean_(p.studentId)&&x.resource_id===r.resource_id;}),v={student_id:clean_(p.studentId),resource_id:r.resource_id,title_override:clean_(p.titleOverride),visible_from:clean_(p.visibleFrom)||date_(),due_date:clean_(p.dueDate),status:'published',created_at:stamp_()};if(old)update_(PORTAL.assignments,old._row,v);else{v.assignment_id=id_('ASN');append_(PORTAL.assignments,v);}audit_('admin',admin.email,'resource_assigned','resource',r.resource_id,clean_(p.studentId));return{assigned:true};}
function dashboardForParent_(parent){var students=childViews_(parent.parent_id);return{children:students,notifications:notifications_(students.map(function(s){return s.student_id;})),upiId:getConfig_('upi_id'),academyName:getConfig_('academy_name')||'Eduwave Academy'};}
function childViews_(parentId){var ids=rows_(PORTAL.links).filter(function(r){return r.parent_id===parentId&&clean_(r.active).toLowerCase()==='true';}).map(function(r){return r.student_id;}),submissions=rows_(PORTAL.submissions);return rows_(PORTAL.students).filter(function(r){return ids.indexOf(r.student_id)!==-1;}).map(function(s){var asns=rows_(PORTAL.assignments).filter(function(r){return r.student_id===s.student_id&&clean_(r.status).toLowerCase()==='published';}),resources=asns.map(function(a){var r=first_(PORTAL.resources,function(x){return x.resource_id===a.resource_id;}),sub=submissions.filter(function(x){return x.assignment_id===a.assignment_id&&x.student_id===s.student_id;})[0];return r?{assignment_id:a.assignment_id,resource_id:r.resource_id,title:a.title_override||r.title,subject:r.subject,kind:r.kind,submission_type:submissionType_(r),due_date:a.due_date,submission_status:sub?sub.status:submissionType_(r)==='view_only'?'view_only':'pending',submitted_at:sub?sub.submitted_at:''}:null;}).filter(Boolean),fees=rows_(PORTAL.fees).filter(function(r){return r.student_id===s.student_id;}).sort(newest_).slice(0,6),attendance=rows_(PORTAL.attendance).filter(function(r){return r.student_id===s.student_id;}).sort(newest_).slice(0,6),progress=rows_(PORTAL.progress).filter(function(r){return r.student_id===s.student_id;}).sort(newest_).slice(0,6);return{student_id:s.student_id,name:s.name,class_level:s.class_level,resources:resources,fees:fees,attendance:attendance,progress:progress};});}
function notifications_(ids){var today=date_(),notes=[],submissions=rows_(PORTAL.submissions);rows_(PORTAL.assignments).filter(function(r){return ids.indexOf(r.student_id)!==-1&&clean_(r.status).toLowerCase()==='published'&&(!r.visible_from||r.visible_from<=today);}).forEach(function(r){var resource=first_(PORTAL.resources,function(x){return x.resource_id===r.resource_id;}),sub=first_(PORTAL.submissions,function(x){return x.assignment_id===r.assignment_id&&x.student_id===r.student_id;});if(!sub||clean_(sub.status).toLowerCase()==='needs_changes')notes.push({type:'assignment',title:sub?'Changes requested':'Pending assignment',message:(resource?resource.title:'A new resource')+(sub&&sub.feedback?' - '+sub.feedback:' is ready to complete.'),student_id:r.student_id});});rows_(PORTAL.fees).filter(function(r){return ids.indexOf(r.student_id)!==-1&&clean_(r.status).toLowerCase()!=='paid';}).forEach(function(r){notes.push({type:'payment',title:'Fee update',message:r.billing_month+' fee of Rs '+r.amount+' is '+r.status+'.',student_id:r.student_id,fee_id:r.fee_id});});rows_(PORTAL.announcements).filter(function(r){return(!r.active_from||r.active_from<=today)&&(!r.active_until||r.active_until>=today)&&(r.audience==='all'||ids.indexOf(r.student_id)!==-1);}).forEach(function(r){notes.push({type:r.type||'exam',title:r.title,message:r.message,student_id:r.student_id});});return notes.slice(0,20);}
function renderDriveItem_(item,resource,parent,studentId,assignment){var file=DriveApp.getFileById(item.drive_id),watermark=parent.name+' | '+stamp_().replace('T',' ').slice(0,16)+' | '+studentId.slice(-4),submission=first_(PORTAL.submissions,function(r){return r.assignment_id===assignment.assignment_id&&r.student_id===studentId;}),meta={assignmentId:assignment.assignment_id,dueDate:assignment.due_date,submissionType:submissionType_(resource),submission:submission?submissionView_(submission):null};if(item.kind==='sheet'){var ss=SpreadsheetApp.openById(item.drive_id),tab=ss.getSheets()[0],lr=Math.min(80,Math.max(1,tab.getLastRow())),lc=Math.min(16,Math.max(1,tab.getLastColumn()));return merge_(meta,{kind:'table',title:resource.title,values:tab.getRange(1,1,lr,lc).getDisplayValues(),watermark:watermark});}if(item.kind==='doc')return merge_(meta,{kind:'text',title:resource.title,text:DocumentApp.openById(item.drive_id).getBody().getText().slice(0,30000),watermark:watermark});if(item.kind==='pdf'||item.kind==='image'){if(Number(item.size_bytes)>MAX_BINARY_BYTES)return merge_(meta,{kind:'notice',title:resource.title,message:'This file is too large for the free portal preview. Ask the academy to publish a smaller PDF or image.'});var blob=file.getBlob();return merge_(meta,{kind:item.kind,title:resource.title,data_url:'data:'+blob.getContentType()+';base64,'+Utilities.base64Encode(blob.getBytes()),watermark:watermark});}if(Number(item.size_bytes)>MAX_BINARY_BYTES)return merge_(meta,{kind:'notice',title:resource.title,message:'This file is too large for secure delivery. Ask the academy for a file under 10 MB.'});var download=file.getBlob(),downloadMime=download.getContentType()||item.mime_type||'application/octet-stream';return merge_(meta,{kind:'download',title:resource.title,file_name:item.name||file.getName(),mimeType:downloadMime,data_url:'data:'+downloadMime+';base64,'+Utilities.base64Encode(download.getBytes()),message:'This file opens in Word, Excel, PowerPoint, or another compatible app.'});}
function renderPortalWorksheet_(resource,parent,studentId,assignment){var rows=rows_(PORTAL.worksheetRows).filter(function(r){return r.resource_id===resource.resource_id;}).sort(function(a,b){return Number(a.row_no)-Number(b.row_no);}),submission=first_(PORTAL.submissions,function(r){return r.assignment_id===assignment.assignment_id&&r.student_id===studentId;}),values=[['No.','Question','Hint']];rows.forEach(function(r){values.push([r.row_no,r.question,r.hint]);});if(values.length===1)throw new Error('This worksheet does not have any questions yet.');return{kind:'table',title:resource.title,values:values,watermark:parent.name+' | '+stamp_().replace('T',' ').slice(0,16)+' | '+studentId.slice(-4),assignmentId:assignment.assignment_id,dueDate:assignment.due_date,submissionType:submissionType_(resource),submission:submission?submissionView_(submission):null};}
function submissionView_(r){var answers=[];try{answers=JSON.parse(r.responses_json||'[]');}catch(_){ }return{submission_id:r.submission_id,assignment_id:r.assignment_id,student_id:r.student_id,resource_id:r.resource_id,answers:answers,student_note:r.student_note,status:r.status,submitted_at:r.submitted_at,updated_at:r.updated_at,reviewed_at:r.reviewed_at,feedback:r.feedback,has_attachment:!!r.attachment_drive_id,attachment_name:r.attachment_name,attachment_mime:r.attachment_mime,attachment_size:Number(r.attachment_size)||0};}
function validSubmissionType_(value,kind){var v=clean_(value).toLowerCase();return['online_answers','file_upload','view_only'].indexOf(v)!==-1?v:(clean_(kind).toLowerCase()==='worksheet'?'online_answers':'file_upload');}
function submissionType_(resource){return validSubmissionType_(resource.submission_type,resource.kind);}
function mimeForName_(name){var ext=(clean_(name).toLowerCase().match(/\.([a-z0-9]+)$/)||[])[1]||'',map={pdf:'application/pdf',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',rtf:'application/rtf',txt:'text/plain'};return map[ext]||'';}
function safeFileName_(name){var safe=clean_(name).replace(/[\\/:*?\"<>|\u0000-\u001F]/g,'_').replace(/\s+/g,' ').slice(0,160);return safe||'upload';}
function parseUpload_(payload,allowed){if(!payload||typeof payload!=='object')throw new Error('Choose a file to upload.');var name=safeFileName_(payload.name),mime=clean_(payload.mimeType).toLowerCase()||mimeForName_(name),data=clean_(payload.data).replace(/^data:[^;]+;base64,/,'');if(allowed.indexOf(mime)===-1)throw new Error('That file type is not supported.');if(!data)throw new Error('The selected file is empty.');var bytes;try{bytes=Utilities.base64Decode(data);}catch(_){throw new Error('The selected file could not be read.');}if(!bytes.length)throw new Error('The selected file is empty.');if(bytes.length>MAX_UPLOAD_BYTES)throw new Error('Choose a file smaller than 8 MB.');return{name:name,mime:mime,bytes:bytes,size:bytes.length};}
function portalUploadRoot_(){var id=getConfig_('portal_upload_root_id'),folder=null;if(id){try{folder=DriveApp.getFolderById(id);}catch(_){folder=null;}}if(!folder){folder=DriveApp.createFolder('Eduwave Portal Uploads');setConfig_('portal_upload_root_id',folder.getId());}return folder;}
function portalUploadFolder_(key,name){var id=getConfig_(key),folder=null;if(id){try{folder=DriveApp.getFolderById(id);}catch(_){folder=null;}}if(!folder){folder=portalUploadRoot_().createFolder(name);setConfig_(key,folder.getId());}return folder;}
function savePortalUpload_(payload,allowed,folderKey,folderName,prefix){var parsed=parseUpload_(payload,allowed),name=safeFileName_((prefix||'')+parsed.name),blob=Utilities.newBlob(parsed.bytes,parsed.mime,name),file=portalUploadFolder_(folderKey,folderName).createFile(blob);return{file:file,name:name,mime:parsed.mime,size:parsed.size};}
function trashFile_(id){try{DriveApp.getFileById(id).setTrashed(true);}catch(_){ }}
function merge_(a,b){Object.keys(b).forEach(function(k){a[k]=b[k];});return a;}
function requireAdmin_(sessionId){var s=session_(sessionId,true,'admin');if(adminEmails_().indexOf(s.email)===-1)throw new Error('This email is not approved for academy access.');return{email:s.email,access_role:academyRole_(s.email)};}
function parentFromSession_(id){var s=session_(id,true,'parent'),p=first_(PORTAL.parents,function(r){return r.parent_id===s.parent_id&&clean_(r.status).toLowerCase()==='active';});if(!p)throw new Error('Parent account is inactive.');return p;}
function session_(id,required,role){var raw=clean_(id),key=raw?authHash_('session|'+raw):'',s=key&&first_(PORTAL.sessions,function(r){return r.session_id===key;});if(!s||role&&s.role!==role){if(required)throw new Error('Your session has ended. Please sign in again.');return null;}var now=new Date(),lastSeen=Date.parse(s.last_seen_at),idle=lastSeen&&!isNaN(lastSeen)?now.getTime()-lastSeen:Infinity,idleLimit=(s.role==='admin'?ADMIN_IDLE_MINUTES:SESSION_IDLE_MINUTES)*60000;if(s.revoked_at||s.expires_at<stamp_(now)||idle>idleLimit){if(!s.revoked_at)update_(PORTAL.sessions,s._row,{revoked_at:stamp_(),revoke_reason:idle>idleLimit?'idle_timeout':'expired'});if(required)throw new Error('Your session has ended. Please sign in again.');return null;}update_(PORTAL.sessions,s._row,{last_seen_at:stamp_()});return s;}
function requireLinkedStudent_(pid,sid){if(!first_(PORTAL.links,function(r){return r.parent_id===pid&&r.student_id===sid&&clean_(r.active).toLowerCase()==='true';}))throw new Error('This child is not linked to your parent account.');}
function parentView_(r){return{parent_id:r.parent_id,name:r.name,email:r.email,phone:r.phone,status:r.status,email_verified:!!r.email_verified_at};}
function ensureHeaders_(name){var sh=sheet_(name,true),wanted=HEADERS[name];if(sh.getLastRow()===0){sh.getRange(1,1,1,wanted.length).setValues([wanted]);return;}var current=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getDisplayValues()[0],missing=wanted.filter(function(h){return current.indexOf(h)===-1;});if(missing.length)sh.getRange(1,current.length+1,1,missing.length).setValues([missing]);}
function sheet_(name,create){var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(name);if(!sh&&create)sh=ss.insertSheet(name);if(!sh)throw new Error('Missing portal tab: '+name+'. Run setupEduwave() once.');return sh;}
function rows_(name){var sh=sheet_(name,false),v=sh.getDataRange().getDisplayValues();if(v.length<2)return[];var h=v[0];return v.slice(1).filter(function(r){return r.some(function(x){return x!=='';});}).map(function(r,i){var o={_row:i+2};h.forEach(function(k,j){o[k]=r[j]||'';});return o;});}
function first_(name,p){return rows_(name).filter(p)[0]||null;}
function append_(name,o){sheet_(name,false).appendRow(HEADERS[name].map(function(k){return o[k]===undefined?'':o[k];}));}
function update_(name,row,values){var sh=sheet_(name,false),h=HEADERS[name],current=sh.getRange(row,1,1,h.length).getDisplayValues()[0];h.forEach(function(k,i){if(values[k]!==undefined)current[i]=values[k];});sh.getRange(row,1,1,h.length).setValues([current]);}
function setConfigDefault_(k,v){if(!getConfig_(k))setConfig_(k,v);}function getConfig_(k){var r=first_(PORTAL.config,function(x){return x.key===k;});return r?r.value:'';}function setConfig_(k,v){var r=first_(PORTAL.config,function(x){return x.key===k;}),o={key:k,value:v,updated_at:stamp_()};if(r)update_(PORTAL.config,r._row,o);else append_(PORTAL.config,o);}
function adminEmails_(){return[(getConfig_('admin_email')||'studywitheduwaveacademy@gmail.com'),(getConfig_('developer_email')||'diwij.narang2001@gmail.com')].join(',').split(',').map(email_).filter(Boolean);}
function academyRole_(email){return(getConfig_('developer_email')||'').split(',').map(email_).indexOf(email_(email))!==-1?'developer':'admin';}
function authSecret_(){var props=PropertiesService.getScriptProperties(),secret=props.getProperty('AUTH_SECRET');if(!secret){secret=token_();props.setProperty('AUTH_SECRET',secret);}return secret;}
function authHash_(value){return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(clean_(value),authSecret_())).replace(/=+$/,'');}
function token_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}
function otp_(){var n=parseInt(Utilities.getUuid().replace(/-/g,'').slice(0,8),16)%1000000;return('000000'+n).slice(-6);}
function safeEqual_(a,b){a=clean_(a);b=clean_(b);if(a.length!==b.length)return false;var diff=0;for(var i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
function mailPermissionError_(err){return/permission|authoriz|script\.send_mail/i.test(String(err&&err.message||err));}
function mailQuota_(){try{return MailApp.getRemainingDailyQuota();}catch(err){if(mailPermissionError_(err))throw new Error('Academy email needs one-time authorization. Run authorizeEduwaveMail in Apps Script, then deploy a new web app version.');throw err;}}
function sendLoginCode_(email,code,role){var academy=getConfig_('academy_name')||'Eduwave Academy',label=role==='admin'?'academy administration':'parent portal',subject=academy+' login code',plain='Your '+academy+' code is '+code+'. It expires in '+OTP_EXPIRY_MINUTES+' minutes. If you did not request this code, ignore this email.',html='<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;padding:28px;color:#1d2a25"><p style="font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#596861">'+academy+' · '+label+'</p><h1 style="font-size:24px">Your secure login code</h1><p>Enter this code on the Eduwave website:</p><p style="font-size:32px;font-weight:700;letter-spacing:.24em;background:#f3f1e8;padding:16px 20px;border-radius:12px">'+code+'</p><p>This code expires in '+OTP_EXPIRY_MINUTES+' minutes and can be used once.</p><p style="color:#596861;font-size:13px">If you did not request it, you can safely ignore this email.</p></div>';try{MailApp.sendEmail({to:email,subject:subject,body:plain,htmlBody:html,name:academy});}catch(err){if(mailPermissionError_(err))throw new Error('Academy email needs one-time authorization. Run authorizeEduwaveMail in Apps Script, then deploy a new web app version.');throw err;}}
function audit_(at,ai,event,et,ei,detail){append_(PORTAL.audit,{event_id:id_('LOG'),actor_type:at,actor_id:ai,event:event,entity_type:et,entity_id:ei,detail:detail,created_at:stamp_()});}
function driveKind_(mime,name){if(mime===MimeType.GOOGLE_SHEETS)return'sheet';if(mime===MimeType.GOOGLE_DOCS)return'doc';if(mime===MimeType.PDF)return'pdf';if(/^image\//.test(mime))return'image';if(/^video\//.test(mime))return'video';if(/\.(docx?|xlsx?|pptx?|rtf)$/i.test(name)||/msword|officedocument|ms-excel|ms-powerpoint|rtf/.test(mime))return'office';return'file';}
function id_(p){return p+'-'+Utilities.getUuid().slice(0,8).toUpperCase();}function clean_(v){return String(v===undefined||v===null?'':v).trim();}function email_(v){return clean_(v).toLowerCase();}function validEmail_(v){var e=email_(v);return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)?e:'';}function hash_(v){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,clean_(v)));}function stamp_(d){return Utilities.formatDate(d||new Date(),TZ,"yyyy-MM-dd'T'HH:mm:ssXXX");}function date_(d){return Utilities.formatDate(d||new Date(),TZ,'yyyy-MM-dd');}function newest_(a,b){return String(b.updated_at||b.created_at||'').localeCompare(String(a.updated_at||a.created_at||''));}function json_(ok,message,data){return ContentService.createTextOutput(JSON.stringify({ok:ok,message:message,data:data||{}})).setMimeType(ContentService.MimeType.JSON);}
