/* Eduwave trial portal. Bind to the academy spreadsheet; run setupEduwave() once. */
const PORTAL = { parents:'Portal_Parents', students:'Portal_Students', links:'Portal_ParentStudents', sessions:'Portal_Sessions', trials:'Portal_Trials', fees:'Portal_Fees', driveIndex:'Portal_DriveIndex', resources:'Portal_Resources', assignments:'Portal_Assignments', attendance:'Portal_Attendance', progress:'Portal_Progress', announcements:'Portal_Announcements', reminders:'Portal_Reminders', audit:'Portal_AuditLogs', config:'Portal_Config' };
const HEADERS = {};
HEADERS[PORTAL.parents] = ['parent_id','name','email','phone','status','created_at','updated_at'];
HEADERS[PORTAL.students] = ['student_id','name','class_level','enrollment_status','monthly_fee','due_day','created_at','updated_at'];
HEADERS[PORTAL.links] = ['link_id','parent_id','student_id','relationship','active','created_at'];
HEADERS[PORTAL.sessions] = ['session_id','parent_id','device_hash','label','created_at','last_seen_at','expires_at','revoked_at','revoke_reason'];
HEADERS[PORTAL.trials] = ['trial_id','child_name','class_level','parent_name','phone','email','subjects','preferred_slot','notes','status','created_at','updated_at'];
HEADERS[PORTAL.fees] = ['fee_id','student_id','billing_month','amount','due_date','status','paid_date','reference','parent_note','updated_at'];
HEADERS[PORTAL.driveIndex] = ['drive_id','parent_drive_id','path','name','mime_type','kind','owner_email','ownership','size_bytes','modified_at','indexed_at','safe_candidate'];
HEADERS[PORTAL.resources] = ['resource_id','drive_id','title','subject','class_level','kind','status','created_at','updated_at'];
HEADERS[PORTAL.assignments] = ['assignment_id','student_id','resource_id','title_override','visible_from','due_date','status','created_at'];
HEADERS[PORTAL.attendance] = ['attendance_id','student_id','session_date','subject','status','note','updated_at'];
HEADERS[PORTAL.progress] = ['progress_id','student_id','subject','topic','score','teacher_note','updated_at'];
HEADERS[PORTAL.announcements] = ['announcement_id','audience','student_id','title','message','type','active_from','active_until','created_at'];
HEADERS[PORTAL.reminders] = ['reminder_id','student_id','type','message','created_at','sent_at','status','whatsapp_url'];
HEADERS[PORTAL.audit] = ['event_id','actor_type','actor_id','event','entity_type','entity_id','detail','created_at'];
HEADERS[PORTAL.config] = ['key','value','updated_at'];
const SESSION_IDLE_MINUTES = 60, SESSION_ABSOLUTE_HOURS = 12, MAX_ACTIVE_DEVICES = 2, MAX_BINARY_BYTES = 10*1024*1024, TZ = Session.getScriptTimeZone() || 'Asia/Kolkata';
function onOpen(){ SpreadsheetApp.getUi().createMenu('Eduwave Portal').addItem('Create portal tabs safely','setupEduwave').addItem('Create this month\'s fee rows','generateMonthlyFees').addToUi(); }
function setupEduwave(){ Object.keys(HEADERS).forEach(function(name){var sh=sheet_(name,true);if(sh.getLastRow()===0)sh.appendRow(HEADERS[name]);});setConfigDefault_('admin_email','studywitheduwaveacademy@gmail.com');setConfigDefault_('drive_root_id','');setConfigDefault_('upi_id','');setConfigDefault_('academy_name','Eduwave Academy');audit_('system','setup','setup','workbook',SpreadsheetApp.getActive().getId(),'Portal tabs created; legacy tabs untouched.');SpreadsheetApp.getUi().alert('Eduwave portal tabs are ready. The old Settings tab was not changed.'); }
function generateMonthlyFees(){var r=generateMonthlyFees_();SpreadsheetApp.getUi().alert('Created '+r.created+' fee row(s) for '+r.month+'.');}
function doGet(){return json_(true,'Eduwave portal API is online.',{version:'2.0',configured:!!getConfig_('admin_email')});}
function doPost(e){try{var p=JSON.parse((e&&e.postData&&e.postData.contents)||'{}'),a=clean_(p.action),d;if(!a)throw new Error('Missing action.');switch(a){case'health':d={version:'2.0',configured:!!getConfig_('admin_email')};break;case'submitTrial':d=submitTrial_(p);break;case'googleLogin':d=googleLogin_(p);break;case'logout':d=logout_(p);break;case'parentDashboard':d=parentDashboard_(p);break;case'parentResource':d=parentResource_(p);break;case'parentPaymentNote':d=parentPaymentNote_(p);break;case'parentEvent':d=parentEvent_(p);break;case'adminDashboard':d=adminDashboard_(p);break;case'adminCreateFamily':d=adminCreateFamily_(p);break;case'adminCreateStudent':d=adminCreateStudent_(p);break;case'adminApproveTrial':d=adminApproveTrial_(p);break;case'adminCreateAnnouncement':d=adminCreateAnnouncement_(p);break;case'adminRecordAttendance':d=adminRecordAttendance_(p);break;case'adminRecordProgress':d=adminRecordProgress_(p);break;case'adminGenerateMonthlyFees':d=generateMonthlyFees_();break;case'adminMarkFeePaid':d=adminMarkFeePaid_(p);break;case'adminQueueReminder':d=adminQueueReminder_(p);break;case'adminScanDrive':d=adminScanDrive_(p);break;case'adminDriveItems':d=adminDriveItems_(p);break;case'adminCreateResource':d=adminCreateResource_(p);break;case'adminAssignResource':d=adminAssignResource_(p);break;default:throw new Error('Unknown action.');}return json_(true,'Success',d);}catch(err){return json_(false,err&&err.message?err.message:'Server error');}}
function submitTrial_(p){['childName','classLevel','parentName','phone','email','subjects','preferredSlot'].forEach(function(k){if(!clean_(p[k]))throw new Error('Please complete all required trial fields.');});var now=stamp_();append_(PORTAL.trials,{trial_id:id_('TRIAL'),child_name:clean_(p.childName),class_level:clean_(p.classLevel),parent_name:clean_(p.parentName),phone:clean_(p.phone),email:email_(p.email),subjects:clean_(p.subjects),preferred_slot:clean_(p.preferredSlot),notes:clean_(p.notes),status:'pending',created_at:now,updated_at:now});audit_('public',email_(p.email),'trial_requested','trial','',clean_(p.childName));return{recorded:true};}
function googleLogin_(p){var identity=verifyGoogleToken_(p.idToken),parent=first_(PORTAL.parents,function(r){return email_(r.email)===identity.email&&clean_(r.status).toLowerCase()==='active';});if(!parent){audit_('parent',identity.email,'login_denied','parent','','Email is not approved.');throw new Error('This Google account is not yet approved for the Eduwave portal.');}var device=clean_(p.deviceId)||'unknown-device',now=new Date(),active=rows_(PORTAL.sessions).filter(function(r){return r.parent_id===parent.parent_id&&!r.revoked_at&&new Date(r.expires_at).getTime()>now.getTime();}).sort(function(a,b){return new Date(a.created_at)-new Date(b.created_at);});while(active.length>=MAX_ACTIVE_DEVICES){var oldest=active.shift();update_(PORTAL.sessions,oldest._row,{revoked_at:stamp_(),revoke_reason:'new_device_login'});audit_('system',parent.parent_id,'session_revoked','session',oldest.session_id,'Maximum active device policy.');}var s={session_id:Utilities.getUuid(),parent_id:parent.parent_id,device_hash:hash_(device),label:clean_(p.deviceLabel)||'Parent device',created_at:stamp_(),last_seen_at:stamp_(),expires_at:stamp_(new Date(now.getTime()+SESSION_ABSOLUTE_HOURS*3600000)),revoked_at:'',revoke_reason:''};append_(PORTAL.sessions,s);audit_('parent',parent.parent_id,'login','session',s.session_id,s.label);return{sessionId:s.session_id,parent:parentView_(parent),dashboard:dashboardForParent_(parent)};}
function logout_(p){var s=session_(p.sessionId,false);if(s)update_(PORTAL.sessions,s._row,{revoked_at:stamp_(),revoke_reason:'logout'});return{loggedOut:true};}
function parentDashboard_(p){var parent=parentFromSession_(p.sessionId);return{parent:parentView_(parent),dashboard:dashboardForParent_(parent)};}
function parentResource_(p){var parent=parentFromSession_(p.sessionId),studentId=clean_(p.studentId);requireLinkedStudent_(parent.parent_id,studentId);var asn=first_(PORTAL.assignments,function(r){return r.student_id===studentId&&r.resource_id===clean_(p.resourceId)&&clean_(r.status).toLowerCase()==='published';});if(!asn)throw new Error('This resource is not assigned to this child.');var resource=first_(PORTAL.resources,function(r){return r.resource_id===asn.resource_id&&clean_(r.status).toLowerCase()==='published';});if(!resource)throw new Error('This resource is not available.');var item=first_(PORTAL.driveIndex,function(r){return r.drive_id===resource.drive_id;});if(!item||clean_(item.safe_candidate).toLowerCase()!=='true')throw new Error('This item has not been approved for portal viewing.');audit_('parent',parent.parent_id,'resource_open','resource',resource.resource_id,studentId);return renderDriveItem_(item,resource,parent,studentId);}
function parentPaymentNote_(p){var parent=parentFromSession_(p.sessionId),sid=clean_(p.studentId);requireLinkedStudent_(parent.parent_id,sid);var fee=first_(PORTAL.fees,function(r){return r.fee_id===clean_(p.feeId)&&r.student_id===sid;});if(!fee)throw new Error('Fee record not found.');if(!clean_(p.reference))throw new Error('Add the UPI reference before submitting.');update_(PORTAL.fees,fee._row,{status:'pending_verification',reference:clean_(p.reference),parent_note:clean_(p.note),updated_at:stamp_()});audit_('parent',parent.parent_id,'payment_note_submitted','fee',fee.fee_id,clean_(p.reference));return{submitted:true};}
function parentEvent_(p){var parent=parentFromSession_(p.sessionId);audit_('parent',parent.parent_id,clean_(p.event).slice(0,60),clean_(p.entityType).slice(0,60),clean_(p.entityId).slice(0,80),clean_(p.detail).slice(0,500));return{logged:true};}
function adminDashboard_(p){var admin=requireAdmin_(p.idToken),fees=rows_(PORTAL.fees),trials=rows_(PORTAL.trials);return{admin:admin,metrics:{parents:rows_(PORTAL.parents).filter(function(x){return clean_(x.status).toLowerCase()==='active';}).length,students:rows_(PORTAL.students).filter(function(x){return clean_(x.enrollment_status).toLowerCase()==='active';}).length,pendingTrials:trials.filter(function(x){return clean_(x.status).toLowerCase()==='pending';}).length,openFees:fees.filter(function(x){return clean_(x.status).toLowerCase()!=='paid';}).length},parents:rows_(PORTAL.parents).map(parentView_),students:rows_(PORTAL.students),trials:trials.sort(newest_),fees:fees.sort(newest_),resources:rows_(PORTAL.resources).sort(newest_),assignments:rows_(PORTAL.assignments).sort(newest_),announcements:rows_(PORTAL.announcements).sort(newest_),reminders:rows_(PORTAL.reminders).sort(newest_).slice(0,50),activity:rows_(PORTAL.audit).sort(newest_).slice(0,50)};}
function adminCreateFamily_(p){var admin=requireAdmin_(p.idToken),email=email_(p.email);if(!email||!clean_(p.name))throw new Error('Parent name and approved Gmail address are required.');if(first_(PORTAL.parents,function(r){return email_(r.email)===email;}))throw new Error('That parent Gmail address already exists.');var parent={parent_id:id_('PAR'),name:clean_(p.name),email:email,phone:clean_(p.phone),status:'active',created_at:stamp_(),updated_at:stamp_()};append_(PORTAL.parents,parent);audit_('admin',admin.email,'parent_created','parent',parent.parent_id,email);return parentView_(parent);}
function adminCreateStudent_(p){var admin=requireAdmin_(p.idToken),parent=first_(PORTAL.parents,function(r){return r.parent_id===clean_(p.parentId);});if(!parent||!clean_(p.name)||!clean_(p.classLevel))throw new Error('Choose a parent and complete the child name and class.');var student={student_id:id_('STU'),name:clean_(p.name),class_level:clean_(p.classLevel),enrollment_status:'active',monthly_fee:clean_(p.monthlyFee),due_day:clean_(p.dueDay)||'10',created_at:stamp_(),updated_at:stamp_()};append_(PORTAL.students,student);append_(PORTAL.links,{link_id:id_('LINK'),parent_id:parent.parent_id,student_id:student.student_id,relationship:clean_(p.relationship)||'Parent',active:'true',created_at:stamp_()});audit_('admin',admin.email,'student_created','student',student.student_id,parent.parent_id);return student;}
function adminApproveTrial_(p){var admin=requireAdmin_(p.idToken),trial=first_(PORTAL.trials,function(r){return r.trial_id===clean_(p.trialId);});if(!trial)throw new Error('Trial request not found.');update_(PORTAL.trials,trial._row,{status:clean_(p.status)||'approved',updated_at:stamp_()});audit_('admin',admin.email,'trial_updated','trial',trial.trial_id,clean_(p.status)||'approved');return{updated:true};}
function adminCreateAnnouncement_(p){var admin=requireAdmin_(p.idToken);if(!clean_(p.title)||!clean_(p.message))throw new Error('Announcement title and message are required.');var a={announcement_id:id_('ANN'),audience:clean_(p.audience)||'all',student_id:clean_(p.studentId),title:clean_(p.title),message:clean_(p.message),type:clean_(p.type)||'notice',active_from:clean_(p.activeFrom)||date_(),active_until:clean_(p.activeUntil),created_at:stamp_()};append_(PORTAL.announcements,a);audit_('admin',admin.email,'announcement_created','announcement',a.announcement_id,a.title);return a;}
function adminRecordAttendance_(p){var admin=requireAdmin_(p.idToken);if(!clean_(p.studentId)||!clean_(p.sessionDate)||!clean_(p.subject))throw new Error('Child, date, and subject are required.');var old=first_(PORTAL.attendance,function(r){return r.student_id===clean_(p.studentId)&&r.session_date===clean_(p.sessionDate)&&r.subject===clean_(p.subject);}),v={student_id:clean_(p.studentId),session_date:clean_(p.sessionDate),subject:clean_(p.subject),status:clean_(p.status)||'present',note:clean_(p.note),updated_at:stamp_()};if(old)update_(PORTAL.attendance,old._row,v);else{v.attendance_id=id_('ATT');append_(PORTAL.attendance,v);}audit_('admin',admin.email,'attendance_saved','student',clean_(p.studentId),clean_(p.status));return{saved:true};}
function adminRecordProgress_(p){var admin=requireAdmin_(p.idToken);if(!clean_(p.studentId)||!clean_(p.subject)||!clean_(p.topic))throw new Error('Child, subject, and topic are required.');var v={progress_id:id_('PROG'),student_id:clean_(p.studentId),subject:clean_(p.subject),topic:clean_(p.topic),score:clean_(p.score),teacher_note:clean_(p.note),updated_at:stamp_()};append_(PORTAL.progress,v);audit_('admin',admin.email,'progress_saved','student',v.student_id,v.topic);return v;}
function generateMonthlyFees_(){var month=Utilities.formatDate(new Date(),TZ,'MMMM yyyy'),created=0;rows_(PORTAL.students).filter(function(r){return clean_(r.enrollment_status).toLowerCase()==='active'&&Number(r.monthly_fee)>0;}).forEach(function(s){if(first_(PORTAL.fees,function(f){return f.student_id===s.student_id&&f.billing_month===month;}))return;var due=new Date();due.setDate(Math.max(1,Math.min(28,Number(s.due_day)||10)));append_(PORTAL.fees,{fee_id:id_('FEE'),student_id:s.student_id,billing_month:month,amount:s.monthly_fee,due_date:date_(due),status:'due',paid_date:'',reference:'',parent_note:'',updated_at:stamp_()});created+=1;});audit_('system','monthly-batch','fees_generated','fee',month,String(created));return{created:created,month:month};}
function adminMarkFeePaid_(p){var admin=requireAdmin_(p.idToken),fee=first_(PORTAL.fees,function(r){return r.fee_id===clean_(p.feeId);});if(!fee)throw new Error('Fee record not found.');update_(PORTAL.fees,fee._row,{status:'paid',paid_date:clean_(p.paidDate)||date_(),reference:clean_(p.reference)||fee.reference,updated_at:stamp_()});audit_('admin',admin.email,'fee_marked_paid','fee',fee.fee_id,fee.student_id);return{paid:true};}
function adminQueueReminder_(p){var admin=requireAdmin_(p.idToken),student=first_(PORTAL.students,function(r){return r.student_id===clean_(p.studentId);});if(!student)throw new Error('Child not found.');var link=first_(PORTAL.links,function(r){return r.student_id===student.student_id&&clean_(r.active).toLowerCase()==='true';}),parent=link&&first_(PORTAL.parents,function(r){return r.parent_id===link.parent_id;});if(!parent||!clean_(parent.phone))throw new Error('An active parent phone number is required for WhatsApp.');var message=clean_(p.message)||'Hello '+parent.name+', this is an Eduwave Academy update for '+student.name+'.',phone=clean_(parent.phone).replace(/[^0-9]/g,'');if(phone.length===10)phone='91'+phone;var url='https://wa.me/'+phone+'?text='+encodeURIComponent(message);append_(PORTAL.reminders,{reminder_id:id_('REM'),student_id:student.student_id,type:clean_(p.type)||'general',message:message,created_at:stamp_(),sent_at:'',status:'queued',whatsapp_url:url});audit_('admin',admin.email,'reminder_queued','student',student.student_id,clean_(p.type)||'general');return{whatsappUrl:url};}
function adminScanDrive_(p){var admin=requireAdmin_(p.idToken),rootId=clean_(p.rootFolderId)||getConfig_('drive_root_id');if(!rootId)throw new Error('Enter the master Drive folder ID first.');var root=DriveApp.getFolderById(rootId);setConfig_('drive_root_id',rootId);var state={count:0,limit:Math.min(500,Math.max(1,Number(p.limit)||250)),owner:admin.email};scanFolder_(root,root.getName(),state);audit_('admin',admin.email,'drive_scanned','drive',rootId,String(state.count));return{indexed:state.count,truncated:state.count>=state.limit};}
function scanFolder_(folder,path,state){if(state.count>=state.limit)return;var folders=folder.getFolders();while(folders.hasNext()&&state.count<state.limit){var child=folders.next();scanFolder_(child,path+' / '+child.getName(),state);}var files=folder.getFiles();while(files.hasNext()&&state.count<state.limit){var file=files.next(),owner='';try{owner=file.getOwner()?file.getOwner().getEmail():'';}catch(ignore){}var owned=owner&&email_(owner)===email_(state.owner),safe=owned&&!/^video\//.test(file.getMimeType()),old=first_(PORTAL.driveIndex,function(r){return r.drive_id===file.getId();}),v={drive_id:file.getId(),parent_drive_id:folder.getId(),path:path,name:file.getName(),mime_type:file.getMimeType(),kind:driveKind_(file.getMimeType(),file.getName()),owner_email:owner,ownership:owned?'academy':'external',size_bytes:String(file.getSize()),modified_at:stamp_(file.getLastUpdated()),indexed_at:stamp_(),safe_candidate:String(safe)};if(old)update_(PORTAL.driveIndex,old._row,v);else append_(PORTAL.driveIndex,v);state.count+=1;}}
function adminDriveItems_(p){requireAdmin_(p.idToken);return rows_(PORTAL.driveIndex).filter(function(r){return clean_(r.ownership)==='academy'&&clean_(r.safe_candidate).toLowerCase()==='true';}).sort(function(a,b){return clean_(a.path+a.name).localeCompare(clean_(b.path+b.name));}).slice(0,500);}
function adminCreateResource_(p){var admin=requireAdmin_(p.idToken),item=first_(PORTAL.driveIndex,function(r){return r.drive_id===clean_(p.driveId);});if(!item||clean_(item.safe_candidate).toLowerCase()!=='true')throw new Error('Choose an academy-owned, non-video file from the indexed Drive list.');var old=first_(PORTAL.resources,function(r){return r.drive_id===item.drive_id;}),v={drive_id:item.drive_id,title:clean_(p.title)||item.name,subject:clean_(p.subject),class_level:clean_(p.classLevel),kind:item.kind,status:'published',updated_at:stamp_()};if(old){update_(PORTAL.resources,old._row,v);return old;}v.resource_id=id_('RES');v.created_at=stamp_();append_(PORTAL.resources,v);audit_('admin',admin.email,'resource_published','resource',v.resource_id,v.title);return v;}
function adminAssignResource_(p){var admin=requireAdmin_(p.idToken);if(!clean_(p.studentId)||!clean_(p.resourceId))throw new Error('Choose a child and a resource.');var r=first_(PORTAL.resources,function(x){return x.resource_id===clean_(p.resourceId)&&clean_(x.status)==='published';});if(!r)throw new Error('Published resource not found.');var old=first_(PORTAL.assignments,function(x){return x.student_id===clean_(p.studentId)&&x.resource_id===r.resource_id;}),v={student_id:clean_(p.studentId),resource_id:r.resource_id,title_override:clean_(p.titleOverride),visible_from:clean_(p.visibleFrom)||date_(),due_date:clean_(p.dueDate),status:'published',created_at:stamp_()};if(old)update_(PORTAL.assignments,old._row,v);else{v.assignment_id=id_('ASN');append_(PORTAL.assignments,v);}audit_('admin',admin.email,'resource_assigned','resource',r.resource_id,clean_(p.studentId));return{assigned:true};}
function dashboardForParent_(parent){var students=childViews_(parent.parent_id);return{children:students,notifications:notifications_(students.map(function(s){return s.student_id;})),upiId:getConfig_('upi_id'),academyName:getConfig_('academy_name')||'Eduwave Academy'};}
function childViews_(parentId){var ids=rows_(PORTAL.links).filter(function(r){return r.parent_id===parentId&&clean_(r.active).toLowerCase()==='true';}).map(function(r){return r.student_id;});return rows_(PORTAL.students).filter(function(r){return ids.indexOf(r.student_id)!==-1;}).map(function(s){var asns=rows_(PORTAL.assignments).filter(function(r){return r.student_id===s.student_id&&clean_(r.status).toLowerCase()==='published';}),resources=asns.map(function(a){var r=first_(PORTAL.resources,function(x){return x.resource_id===a.resource_id;});return r?{assignment_id:a.assignment_id,resource_id:r.resource_id,title:a.title_override||r.title,subject:r.subject,kind:r.kind,due_date:a.due_date}:null;}).filter(Boolean),fees=rows_(PORTAL.fees).filter(function(r){return r.student_id===s.student_id;}).sort(newest_).slice(0,6),attendance=rows_(PORTAL.attendance).filter(function(r){return r.student_id===s.student_id;}).sort(newest_).slice(0,6),progress=rows_(PORTAL.progress).filter(function(r){return r.student_id===s.student_id;}).sort(newest_).slice(0,6);return{student_id:s.student_id,name:s.name,class_level:s.class_level,resources:resources,fees:fees,attendance:attendance,progress:progress};});}
function notifications_(ids){var today=date_(),notes=[];rows_(PORTAL.assignments).filter(function(r){return ids.indexOf(r.student_id)!==-1&&clean_(r.status).toLowerCase()==='published'&&(!r.visible_from||r.visible_from<=today);}).forEach(function(r){var resource=first_(PORTAL.resources,function(x){return x.resource_id===r.resource_id;});notes.push({type:'assignment',title:'New assignment',message:(resource?resource.title:'A new resource')+' is ready to view.',student_id:r.student_id});});rows_(PORTAL.fees).filter(function(r){return ids.indexOf(r.student_id)!==-1&&clean_(r.status).toLowerCase()!=='paid';}).forEach(function(r){notes.push({type:'payment',title:'Fee update',message:r.billing_month+' fee of Rs '+r.amount+' is '+r.status+'.',student_id:r.student_id,fee_id:r.fee_id});});rows_(PORTAL.announcements).filter(function(r){return(!r.active_from||r.active_from<=today)&&(!r.active_until||r.active_until>=today)&&(r.audience==='all'||ids.indexOf(r.student_id)!==-1);}).forEach(function(r){notes.push({type:r.type||'exam',title:r.title,message:r.message,student_id:r.student_id});});return notes.slice(0,20);}
function renderDriveItem_(item,resource,parent,studentId){var file=DriveApp.getFileById(item.drive_id),watermark=parent.name+' | '+stamp_().replace('T',' ').slice(0,16)+' | '+studentId.slice(-4);if(item.kind==='sheet'){var ss=SpreadsheetApp.openById(item.drive_id),tab=ss.getSheets()[0],lr=Math.min(80,Math.max(1,tab.getLastRow())),lc=Math.min(16,Math.max(1,tab.getLastColumn()));return{kind:'table',title:resource.title,values:tab.getRange(1,1,lr,lc).getDisplayValues(),watermark:watermark};}if(item.kind==='doc')return{kind:'text',title:resource.title,text:DocumentApp.openById(item.drive_id).getBody().getText().slice(0,30000),watermark:watermark};if(item.kind==='pdf'||item.kind==='image'){if(Number(item.size_bytes)>MAX_BINARY_BYTES)return{kind:'notice',title:resource.title,message:'This file is too large for the free portal preview. Ask the academy to publish a smaller PDF or image.'};var blob=file.getBlob();return{kind:item.kind,title:resource.title,data_url:'data:'+blob.getContentType()+';base64,'+Utilities.base64Encode(blob.getBytes()),watermark:watermark};}return{kind:'notice',title:resource.title,message:'This format needs an academy conversion to Google Docs or PDF before it can be viewed securely.'};}
function verifyGoogleToken_(idToken){if(!clean_(idToken))throw new Error('Sign in with the approved Google account first.');var response=UrlFetchApp.fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(idToken),{muteHttpExceptions:true});if(response.getResponseCode()!==200)throw new Error('Google sign-in could not be verified. Please sign in again.');var t=JSON.parse(response.getContentText()),expected=PropertiesService.getScriptProperties().getProperty('GOOGLE_CLIENT_ID');if(expected&&t.aud!==expected)throw new Error('Google sign-in is not configured for this portal.');if(String(t.email_verified)!=='true')throw new Error('Use a verified Google account.');return{email:email_(t.email),name:clean_(t.name)};}
function requireAdmin_(idToken){var identity=verifyGoogleToken_(idToken),allowed=(getConfig_('admin_email')||'').split(',').map(email_);if(allowed.indexOf(identity.email)===-1)throw new Error('This Google account is not the Eduwave administrator.');return identity;}
function parentFromSession_(id){var s=session_(id,true),p=first_(PORTAL.parents,function(r){return r.parent_id===s.parent_id&&clean_(r.status).toLowerCase()==='active';});if(!p)throw new Error('Parent account is inactive.');return p;}
function session_(id,required){var s=first_(PORTAL.sessions,function(r){return r.session_id===clean_(id);});if(!s){if(required)throw new Error('Your session has ended. Please sign in again.');return null;}var now=new Date(),idle=now.getTime()-new Date(s.last_seen_at).getTime();if(s.revoked_at||now.getTime()>new Date(s.expires_at).getTime()||idle>SESSION_IDLE_MINUTES*60000){if(!s.revoked_at)update_(PORTAL.sessions,s._row,{revoked_at:stamp_(),revoke_reason:idle>SESSION_IDLE_MINUTES*60000?'idle_timeout':'expired'});if(required)throw new Error('Your session has ended. Please sign in again.');return null;}update_(PORTAL.sessions,s._row,{last_seen_at:stamp_()});return s;}
function requireLinkedStudent_(pid,sid){if(!first_(PORTAL.links,function(r){return r.parent_id===pid&&r.student_id===sid&&clean_(r.active).toLowerCase()==='true';}))throw new Error('This child is not linked to your parent account.');}
function parentView_(r){return{parent_id:r.parent_id,name:r.name,email:r.email,phone:r.phone,status:r.status};}
function sheet_(name,create){var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(name);if(!sh&&create)sh=ss.insertSheet(name);if(!sh)throw new Error('Missing portal tab: '+name+'. Run setupEduwave() once.');return sh;}
function rows_(name){var sh=sheet_(name,false),v=sh.getDataRange().getDisplayValues();if(v.length<2)return[];var h=v[0];return v.slice(1).filter(function(r){return r.some(function(x){return x!=='';});}).map(function(r,i){var o={_row:i+2};h.forEach(function(k,j){o[k]=r[j]||'';});return o;});}
function first_(name,p){return rows_(name).filter(p)[0]||null;}
function append_(name,o){sheet_(name,false).appendRow(HEADERS[name].map(function(k){return o[k]===undefined?'':o[k];}));}
function update_(name,row,values){var sh=sheet_(name,false),h=HEADERS[name],current=sh.getRange(row,1,1,h.length).getDisplayValues()[0];h.forEach(function(k,i){if(values[k]!==undefined)current[i]=values[k];});sh.getRange(row,1,1,h.length).setValues([current]);}
function setConfigDefault_(k,v){if(!getConfig_(k))setConfig_(k,v);}function getConfig_(k){var r=first_(PORTAL.config,function(x){return x.key===k;});return r?r.value:'';}function setConfig_(k,v){var r=first_(PORTAL.config,function(x){return x.key===k;}),o={key:k,value:v,updated_at:stamp_()};if(r)update_(PORTAL.config,r._row,o);else append_(PORTAL.config,o);}
function audit_(at,ai,event,et,ei,detail){append_(PORTAL.audit,{event_id:id_('LOG'),actor_type:at,actor_id:ai,event:event,entity_type:et,entity_id:ei,detail:detail,created_at:stamp_()});}
function driveKind_(mime,name){if(mime===MimeType.GOOGLE_SHEETS)return'sheet';if(mime===MimeType.GOOGLE_DOCS)return'doc';if(mime===MimeType.PDF)return'pdf';if(/^image\//.test(mime))return'image';if(/^video\//.test(mime))return'video';if(/\.docx?$/i.test(name))return'office';return'file';}
function id_(p){return p+'-'+Utilities.getUuid().slice(0,8).toUpperCase();}function clean_(v){return String(v===undefined||v===null?'':v).trim();}function email_(v){return clean_(v).toLowerCase();}function hash_(v){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,clean_(v)));}function stamp_(d){return Utilities.formatDate(d||new Date(),TZ,"yyyy-MM-dd'T'HH:mm:ss");}function date_(d){return Utilities.formatDate(d||new Date(),TZ,'yyyy-MM-dd');}function newest_(a,b){return String(b.updated_at||b.created_at||'').localeCompare(String(a.updated_at||a.created_at||''));}function json_(ok,message,data){return ContentService.createTextOutput(JSON.stringify({ok:ok,message:message,data:data||{}})).setMimeType(ContentService.MimeType.JSON);}
