const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const acorn = require('acorn');

const root = path.resolve(__dirname, '..');

// Bundle only static, relative CommonJS imports. No dependency downloads, eval,
// minification, or runtime loader requests are involved.
function bundleFrontend() {
  const modules = new Map();
  function visit(relative) {
    const id = relative.replaceAll('\\', '/');
    if (modules.has(id)) return;
    const absolute = path.resolve(root, id);
    if (!absolute.startsWith(path.join(root, 'src') + path.sep)) {
      throw new Error(`Frontend import escapes src: ${id}`);
    }
    const source = fs.readFileSync(absolute, 'utf8');
    const ast = acorn.parse(source, { ecmaVersion: 'latest' });
    const imports = Object.create(null);
    function walk(node) {
      if (!node || typeof node !== 'object') return;
      if (node.type === 'CallExpression' && node.callee.name === 'require') {
        const request = node.arguments[0]?.value;
        if (node.arguments.length !== 1 || typeof request !== 'string' || !request.startsWith('.')) {
          throw new Error(`Only static relative imports are supported: ${id}`);
        }
        imports[request] = path.posix.normalize(path.posix.join(path.posix.dirname(id), request));
      }
      for (const value of Object.values(node)) {
        if (Array.isArray(value)) value.forEach(walk);
        else if (value && typeof value === 'object') walk(value);
      }
    }
    walk(ast);
    modules.set(id, {source, imports});
    Object.values(imports).forEach(visit);
  }
  visit('src/main.cjs');
  const entries = [...modules].map(([id, {source, imports}]) =>
    `${JSON.stringify(id)}: [function(module, exports, require) {\n${source}\n}, ${JSON.stringify(imports)}]`
  ).join(',\n');
  const output = `// GENERATED by node tools/build.cjs. Edit src/ instead.\n(() => {\n'use strict';\nconst modules = {\n${entries}\n};\nconst cache = Object.create(null);\nfunction load(id) {\n  if (cache[id]) return cache[id].exports;\n  const [factory, imports] = modules[id];\n  const module = cache[id] = {exports: {}};\n  factory(module, module.exports, request => load(imports[request]));\n  return module.exports;\n}\nload('src/main.cjs');\n})();\n`;
  new vm.Script(output, {filename: 'script.js'});
  return output;
}

function bundleBackend() {
  const files = JSON.parse(fs.readFileSync(path.join(root, 'apps-script/modules.json'), 'utf8'));
  const source = files.map(file => {
    const absolute = path.resolve(root, 'apps-script', file);
    if (!absolute.startsWith(path.join(root, 'apps-script/src') + path.sep)) throw Error(`Invalid backend path: ${file}`);
    return fs.readFileSync(absolute, 'utf8').trimEnd();
  }).join('\n\n');
  new vm.Script(source, {filename: 'Code.gs'});
  return '// GENERATED by node tools/build.cjs. Edit apps-script/src/ instead.\n' + source + '\n';
}

function build({check = false, frontendOnly = false} = {}) {
  const outputs = {'script.js': bundleFrontend()};
  if (!frontendOnly) outputs['apps-script/Code.gs'] = bundleBackend();
  for (const [file, source] of Object.entries(outputs)) {
    const target = path.join(root, file);
    if (check) {
      if (fs.readFileSync(target, 'utf8') !== source) throw Error(`${file} is stale; run node tools/build.cjs`);
    } else fs.writeFileSync(target, source);
  }
  return Object.keys(outputs);
}

module.exports = {build, bundleFrontend, bundleBackend};
if (require.main === module) {
  console.log(build({check: process.argv.includes('--check'), frontendOnly: process.argv.includes('--frontend-only')}).join(', ') + (process.argv.includes('--check') ? ': up to date' : ': built'));
}
