apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eduwave
resources:
  - namespace.yaml
  - web.yaml
  - scaling.yaml
  - ingress.yaml
  - network-policy.yaml
images:
  - name: eduwave-web
    newName: ghcr.io/edu-waveacademy/website
    newTag: REPLACE_WITH_RELEASE
